### ISSUE TITLE
Small Grants: Application - Translation

### ISSUE THREAD

**Issue by aaronhkg** [LIT-Protocol/LitGrants#1]
### 1. What is your project? (max 100 words)

 Chinese translation of the whole documentation and blog posts for Chinese members

 N/A
 N/A

### 2. How is Lit used for this project? (max 100 words)

There is a huge number of Chinese members in the discord channel and yet there is limited access of the information about Lit due to language barrier and lack of native language documentation. Lit would benefit from attracting more talented developers to further expand its ecosystem 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Lit Protocol would be the main beneficiary of this project, the first step would be translating the whole existing documentation in correct terminology. Blog posts and educational videos (captions) would be the next step if time is allowed.
 
### 4. Is this project open source?

Yes, it will be open source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?

Yes, would keep you updated on each section being translated for verification and review

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Lit Protocol prizes? Include links here if available:

No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our grant program?

From your Twitter post

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal, OpenSea)
  * Please link to your submission

**Comment by debbly** [comment]
Hi, thank you for submitting a grant application! Some comments:

1. How much will you need to complete the project? Please give a breakdown of costs.

2. Can you link to work you have done in the past (translation related preferred)?

3. Please complete more about yourself or how you are qualified to complete this project.
