### ISSUE TITLE
Small Grants: decode.chat

### ISSUE THREAD

**Issue by 0xSilkRoad** [LIT-Protocol/LitGrants#10]
### 1. What is your project? (max 100 words)
"decode.chat", a simple decentralized chat dApp that enabling wallet-to-wallet(s) secure messaging.

* GitHub - https://github.com/teapartylife/decode-chat-app
* Website - https://decode.chat

### 2. How is Lit used for this project? (max 100 words)
Lit is used to encrypt+decrypt the entire chat messages between senders and recipients in real-time.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Project already integrated Lit. Grant received will be used to cover initial cost, adding feature for chatrooms encryptions and writing clear step-by-step tutorials to encourage more devs into Lit.
 
### 4. Is this project open source?
Yes, under MIT licence.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Yes.

### 6. Links and submissions
N/A

### 7. Total Budget Requested
Under small grant category: $3000
Breakdown evenly below:
- Milestone 1: Understand how the underlying functions of Lit protocol
- Milestone 2: Integrating Lit Encrypt and Decrypt methods + implement access control (wallet-to-wallet messaging)
- Milestone 3: Implement the similar methods above (encrypt+decrypt) to chatrooms (wallets-to-wallets messaging)
- Milestone 4: Summarise above implementations and condense it into simple boilerplate with clear step-by-step tutorial explanation
  
### Additional questions:
* 0xSilkRoad, 0xsilkroad@protonmail.com, [github.com/0xsilkroad](https://github.com/0xsilkroad), developer.
* How did you learn about our grant program?
  * Via Lit protocol docs
* If your project was created as part of an event or hackathon:
  * N/A

**Comment by debbly** [comment]
Hi @0xSilkRoad, we don't do retroactive funding at the moment and I see that you've already built with Lit. Would you be interested in building out an SDK that utilizes Lit with your chat functionality?
