### ISSUE TITLE
Small Grants: SelfGuard

### ISSUE THREAD

**Issue by ArjunRajJain** [LIT-Protocol/LitGrants#12]
### 1. What is your project? (max 100 words)
SelfGuard uses encryption infrastructure to provide developers tools to build better and more secure UI/UX for their users. Some of these tools include Encrypted Notifications & Encrypted File Storage. 

Website -> https://selfguard.xyz. 
SDK -> https://github.com/selfguard/selfguard 

### 2. How is Lit used for this project? (max 100 words)
I intend to use Lit to handle the storage of the encryption keys on behalf of SelfGuard. Currently they are being stored using Shamir's Secret Sharing. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
After speaking with David, I intend to use this grant to convert the encryption key storage for my Encrypted Notifications module to use Lit Protocol instead of our own backend. Upon success of this conversion, further SelfGuard tools and modules can be converted to using Lit Protocol.  

### 4. Is this project open source?
As of now it is not, parts of the project will definitely be open sourced. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Yes 

### 6. Links and submissions
No

### 7. Total Budget Requested
* Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Applying for $3,000 to handle the conversion from the current encryption key management setup to that of Lit Protocol's. Ideally I want this to be one of the example modules that shows how Lit Protocol is the underlying service provider for all dapp notifications. 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
Arjun Raj Jain (arjun@selfguard.xyz) (https://github.com/selfguard/) CEO. 

* How did you learn about our grant program? Speaking with David (CEO of Lit)

* If your project was created as part of an event or hackathon: N/A
  * What was the name of the event? (e.g. ETHGlobal, OpenSea)
  * Please link to your submission

**Comment by debbly** [comment]
Hi Arjun, great proposal and project idea.

A question about this project - I see that you're using IPFS to store file data. What's the plan for data persistency?

**Comment by ArjunRajJain** [comment]
Hi @debbly sorry about the late response (need to activate Github notifications).  So I'm actually working with the IPFS team internally to offer a backup of all the files (the API i'm using from them is that of web3.storage, and they are currently backing up all files on AWS S3). However a backup solution is in the works to hedge the storage of the files on projects like Arweave or Storj, or even centralized providers like AWS S3.

**Comment by debbly** [comment]
Awesome, how do these milestones sound:

Milestone 1:
$1.5k released once complete
Integration of Lit

Milestone 2:
$1.5k released once complete
Data pinning/data persistence and open sourcing the Lit specific code

**Comment by ArjunRajJain** [comment]
Hey that sounds great, and just to be specific this will be the integration of Lit for the encrypted file storage module. 

This will ensure that users who use the encrypted file storage module with Metamask will have their underlying encryption keys stored with Lit Protocol, the files stored on IPFS (and backed up), and the associations of the files to the encryption keys stored with SelfGuard. 

The underlying SDK of the encryption and file storage APIs will be open sourced, but the backend storage of the associations of files to keys, will remain with SelfGuard.

**Comment by debbly** [comment]
Awesome, we're approving the grant :). 

Will follow up through telegram and email.
