### ISSUE TITLE
Small Grants: Private social graph

### ISSUE THREAD

**Issue by yayashuxue** [LIT-Protocol/LitGrants#16]
### 1. What is your project? (max 100 words)
A social graph is like decentralized identifiers owned by users, but specifically, it's a private social graph that users can have access control over what information they chose to share with others. 

### 2. How is Lit used for this project? (max 100 words)
The lit protocol will be the main technic to be used for social graph access control.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This grant will help us land from concept/design progress to MVPs by supporting our living financially. We are also really ambitious after chatting with the founder of lit Procol, David, about the possibility of this project scaling up, but at that stage, further grant/investment will be needed.
 
### 4. Is this project open source?
The private social graph infrastructure will be open source. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Lit Protocol prizes? Include links here if available:
Nope.

### 7. Total Budget Requested
* Sum up the requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you plan to spend these funds.
$1000 UIUX Designer budget (need to outsource)
$1500 Dev budget
Goal: an MVP.

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
1.  julie, jyshi1107@gmail.com, @yayashuxue. Product
2. jason, jasonfeng1024@gmail.com, @jasonfenggit. Dev
3. harry, haoruikun@icloud.com, @haoruikun. Dev

* How did you learn about our grant program?
Through meeting with David.
 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal, OpenSea)
  In the upcoming Eth San Francisco
  * Please link to your submission

**Comment by debbly** [comment]
Following up, a request on our end is for the Lit integration to be open source! What are your plans to open source this project?

**Comment by yayashuxue** [comment]
Hey @debbly - yes:)!

**Comment by debbly** [comment]
@yayashuxue Awesome, breaking down your grant into milestones:

Milestone #1 
open source SDK/Module for a private social graph MVP
web application to demo MVP

Milestone #2
UI/UX iteration
documentation (+ we'd love to see a blog post or video going through your application so that we can help to market this product!)

We're open to doing $1k upfront, then $750 for each milestone completion. Please let me know your thoughts!

**Comment by yayashuxue** [comment]
@debbly 
Hi Debbie, sorry for the late reply! For the grant yes! But just to confirm with the idea: the idea has evolved through our encounters with people's needs Eth San Francisco Hackathon: can we do ENS subdomain-based access control that implemented lit protocol so that it would be really important for DAO and web3 org management? 

Pls lmk asap if you guys are ok with this idea evolvement and once confirm we can start working on it as the Eth San Francisco Hackathon just started.

**Comment by debbly** [comment]
Hi! Following up on this - if you have any updates to the grant after the hackathon, please update the grant application otherwise I will close this grant and your team is welcome to apply for another grant. 

We are looking to support open source tooling for Lit's access control and the proposed hackathon project does not fall under the types of projects we are focused on.

**Comment by yayashuxue** [comment]
Hey! 
An update: Just won the finalist in Eth San Francisco with my lately proposed idea and loads of sponsor prizes! check out: https://ethglobal.com/showcase/org3-rxvhj. 
I am unsure about how this thread goes, and I met David at the ETHSF and he is really excited about a long-term partnership. Love to circle more around this topic!

**Comment by debbly** [comment]
Yes! Let's talk more about what a partnership looks like for now I'm going to close this grant. Your team is welcome to open another grant in the future.
