### ISSUE TITLE
Small Grants: Krebit issuer of credentials authorized using Lit Actions

### ISSUE THREAD

**Issue by krebit** [LIT-Protocol/LitGrants#19]
### 1. What is your project? (max 100 words)

Krebit provides a Verifiable Credentials protocol, that helps you import your reputation and earn money with your talent and network.

We believe in Decentralization as a means for preserving privacy and having a more meritocratic world. 

Github repos: https://github.com/KrebitDAO

Website: https://krebit.id/

### 2. How is Lit used for this project? (max 100 words)

In Krebit credentials, the user's Personal Identifiable Information (PII) is encrypted using the Lit protocol. Users are in full control on which credentials are public and which ones are encrypted for certain people using the access control conditions. 

During the verification process, the user gives temporarily access to the verification node, who checks the proofs provided by the user and issues the verifiable credential.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Using Lit actions to decentralize the Issuer signatures:

Currently our path for decentralization of the krebit protocol counts on adding more verifiation nodes to the network. Each of those nodes would be added by issuing partners that own a minumun number of KRB tokens, and they stake them as a warranty of the credentials they are signing.

With Lit actions, the krebit DAO can own a set of PKPs and assig them to issuer functions that are transparent with auditable javascript code, and run by issuer partners that want to join the network.

The auth metods and conditions for issuing credentials can then be easier to update and more flexible than today.

Steps:

1. Port the verification and signing part of existing Krebit API endpoints as Lit actions (https://github.com/KrebitDAO/krebit/tree/develop/apps/api/src/controller).

2. Add conditions to the Lit actions for checking who is a valid Issuer to let them sign the credentials using the PKP key. 

3. Create PKPs and add persmission to run those actions.  Then transfer the PKP ownership to the future Krebit DAO for governance.

 
### 4. Is this project open source?

All of our code is released with MIT license

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?

yes

### 6. Links and submissions

Our project began as a gitcoin grant: https://gitcoin.co/grants/3522/krebit-web3-verifiable-credentials

Already integrated with Orbis: https://t.co/HfLZjgmaVF

### 7. Total Budget Requested

* 90 hours of Fullstack Javascript Developer
* 30 hours of Web3 Developer

Total: $3,000
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

* Alerios <aleriospresidente@gmail.com>, https://github.com/orgs/KrebitDAO/people/alerios, Krebit founder and Web3 Developer
* Andres Montoya <andresmontoyafcb@gmail.com>, https://github.com/orgs/KrebitDAO/people/MontoyaAndres, Fullstack Javascript Developer

* How did you learn about our grant program?

Lit core team

**Comment by debbly** [comment]
Awesome, I'm seeing this as 3 milestones, basically one for each step:

1. Port the verification and signing part of existing Krebit API endpoints as Lit actions (https://github.com/KrebitDAO/krebit/tree/develop/apps/api/src/controller).

2. Add conditions to the Lit actions for checking who is a valid Issuer to let them sign the credentials using the PKP key.

3. Create PKPs and add persmission to run those actions. Then transfer the PKP ownership to the future Krebit DAO for governance.

I see the payments being evenly split 1/3rd at each milestone, with payment at milestone completion. Thoughts?

**Comment by krebit** [comment]
Hi @debbly ,
That's correct, we would have 1 milestone per step, so those would be 3 milestones for this project, and payment after each milestone completion.
Thanks,
Alejandro from Krebit

**Comment by debbly** [comment]
Awesome! Approving this grant and someone from our team will send you a contract tomorrow :)
