### ISSUE TITLE
Small Grants: DACEData

### ISSUE THREAD

**Issue by hakymulla** [LIT-Protocol/LitGrants#23]
### 1. What is your project? (max 100 words)

DACEdata also know as Decentralised Access Control Encrypted data is a platform that allows users to

      1. Store data in a decentralised database such as Filecoin's IPFS.
      3. Encrypt and lock data using an on chain condition.
      3. Decrypt locked data based on the given on chain condition.

https://github.com/hakymulla/DaceData

https://youtu.be/gyZMG-PGp3c

### 2. How is Lit used for this project? (max 100 words)

Encrypt and lock data using an on chain condition.
Decrypt locked data based on the given on chain condition.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Merge DaceData and my Bhealth project(https://github.com/hakymulla/ChainLink_Hackathon_2022). This allows patients have full access to their medical data. Patients can give access or revoke physicians/doctors access.

Build a front end.
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Lit Protocol prizes? Include links here if available:

### 7. Total Budget Requested

$2,500

Frontend  $1,000
Backend $1,500

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our grant program?
   https://developer.litprotocol.com/Ecosystem/litGrants
* If your project was created as part of an event or hackathon:
  Polygon Africa Bootcamp 2020

**Comment by debbly** [comment]
Hi @hakymulla, at this time we do not fund access control integrations.
