### ISSUE TITLE
vvSmall Grants: Tell it–Together publishing <> Lens <> Ltt

### ISSUE THREAD

**Issue by hroyo** [LIT-Protocol/LitGrants#24]
Welcome to Tell it–Together. We are about to launch Crypto-Z in partnership with Lens & Seed Club.
Thank you for considering our grant application to launch the first story-RPG publishing DAO. 
https://smashcode-tellittogether.netlify.app/

[TTG – Platform Crypto-Z 0912.pdf](https://github.com/LIT-Protocol/LitGrants/files/10188257/TTG.Platform.Crypto-Z.0912.pdf)

### 1. What is your project? (max 100 words)
Crypto-Z started as a hit podcast (+350K dw) co-created by NYTimes Bestselling author Danielle Trussoni and got a TV development deal at Disney before we decided to turn it into a DAO.This project aims to integrate Lit Protocol in the Crypto-Z publishing platform backed by Lens Protocol & Seed Club Accelerator. Crypto-Z is a X-Files meets Jurrassic Park sci-fi universe in which you can create and own your characters, assets and choose-your-own-adventures. Writers can self-publish in a Wattpad fashion - but most importantly benefit from the network of effect of Lens but also the community behind the IP.  Integrating Lit would allow to onboard existing audience/users/fans and create an RPG like membership experiences in which characters can gain new levels of access and content by participating on the platform.

### 2. How is Lit used for this project? (max 100 words)
Lit Protocol would be used as the access control layer to various content displayed in Crypto-Z platform. Consumer facing login (= non-crypto native) with a Lit module that facilitates sign on / account generation process. A Lit module that supports Lit Actions for posts on Lens  (using your PKP to publish a post on lens / collect a post on lens). A front-end NFT transfer to help move previoulsy collected Lens NFTs to the newly PKP. Token-Gated Content Lit Action & Membership Access NFT token to premium content. Use Access Control to allow three in-game roles and status.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Fund our development to integrate all the Lit Protocol function described above. 
Deliverables:
1 – Milestone: Account Creation Lit module that facilitates sign on / account generation process  
2 – Milestone: Access Control Lit Action - Membership Access NFT 
3 – Milestone: Governance (signature approvals & roles) Lit Action + NFT in-game roles 
« Junior » Can Read / Publish / Collect on Lens
« Agent » Can Vote - Approve « Original » Content via Signature
« Special Agent » Can Approve proposal - funding / Multi-Sig
4 – Milestone: Walletconnect integration - PKP to Lens Profile Creation Flow – Web Reader App with token-gated content (app store and android)

 
### 4. Is this project open source?
n/a we are storytelling project but with Open Source opportunities

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Sure

### 6. Links and submissions
staging (pre-launch)
https://smashcode-tellittogether.netlify.app/
https://open.spotify.com/show/4C1BI786MlUJZoAdmJ3wQt
www.crypto-z.com

### 7. Total Budget Requested
$5K
Funding allocation:  Dev team 2-4, part-time, 2months - Lit migration to Mainnet

Reactjavascript for the frontend
Google Firebase as a backend
Firebase Realtime database 
lens api integration and some other libraries for frontend or data visualisation as well like graph library for graphs and similar and if there is need to store image i will use Firebase cloud storage as well
Arweave or IPFS for user created content no supported by Lens api. 

  
### Additional questions:
Hadrien Royo - founder & ceo of Tell it–Together
hadrien@tellittogther.com 

Ismail Muhammed – Lead dev
Full Stack Developer
https://github.com/ismailmuhammed

Harry Nicholls – NFT dev 
Full Stack Developer
https://github.com/hnipps

Partners: 
Lens Protocol Accelerator
Seed Club Accelerator SC03 https://seedclub.xyz/
Gitcoin Kernel KB3 https://kernel.community/

**Comment by debbly** [comment]
Hi @hroyo,

Can you give a breakdown of the milestones and what engineering work it would take for each portion? I'd also like to see an explanation of how each section intends to use PKPs and Lit Actions! 

Deliverables:
1 – Milestone: Account Creation Lit module that facilitates sign on / account generation process
2 – Milestone: Access Control Lit Action - Membership Access NFT
3 – Milestone: Governance (signature approvals & roles) Lit Action + NFT in-game roles

We generally do not fund integrations without some part of it being open source, what open source opportunities do you see? We generally like to have the Lit specific portions be open sourced so that other people can build on top or extend its use case.

**Comment by hroyo** [comment]
Hi Debie

Eli and I are working on all these for the platform. Lit being new on
testnet we are working on the best approach.
The context been highly narrative and storytelling based
would you be open if I answered those questions over Zoom?

I believe I submitted a PDF as well let me know if it got to you or if I
should resubmit it.
