### ISSUE TITLE
Small Grants: Decentralized Micro Task Platform

### ISSUE THREAD

**Issue by texochat** [LIT-Protocol/LitGrants#27]
### 1. What is your project? (max 100 words)
We will develope a portal where different types of tasks can get done and shows other platform tasks  as well. 
Where we have two types of users .
The first type of user submits tasks here as an employer. 

The second user will apply for tasks and then the first user will accept and reject the  application of the second user. And if second user complete there tasks they will submit there assignment to employer.

Then employer will check if tasks is done according to requirement or not if its done then employer can release payment to second user.

### 2. How is Lit used for this project? (max 100 words)
Lit Protocol will be used to encrypt & decrypt users profile. Users can choose to hide and show their personal information from public.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The grant will be used to develop whole project that will cover development cost.
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Yes

### 6. Links and submissions
N/A

### 7. Total Budget Requested
2000 USD
Funds will be used to cover developers cost
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our grant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal, OpenSea)
  * Please link to your submission
Akhilesh Mishra CEO: https://twitter.com/mishraritz
Would like to share team details over chat (TG: @akhilesh010)

**Comment by debbly** [comment]
Hi @texochat, 
Currently, we are not focused on access control integrations and are looking to fund open source tooling that extends the use cases and usability of Lit. We are more than happy to support on Discord and answer any questions you might have about integrating Lit. 

Debbie
