### ISSUE TITLE
Lit SDK for iOS - Phase #1 - Google authentication and transaction signing / broadcasting with PKPs

### ISSUE THREAD

**Issue by j-labs-xyz** [LIT-Protocol/LitGrants#29]
# Open Grant Proposal: `Lit SDK for iOS - Phase #1`

**Name of Project:** `Lit SDK for iOS - Phase #1 - Google authentication and transaction signing / broadcasting with PKPs`

**Proposal Category:** `Developer tools and libraries`

**Proposer:** `J Labs`

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`

# Project Description

We would like anyone with an iPhone and Google account to be able to sign in and start transacting on blockchains without needing to manage private key or seed phrase.

## Value

Mobile is essential for mass adoption for Web3 and Lit Protocol. 

## Deliverables

We would deliver Lit SDK for iOS in the form of a Swift library which can be integrated in other iOS apps, as well as an iOS app using the library to demonstrate that the user is able to log in to his Google account and transact with PKPs.

### The following functionality would be implemented on iOS in Swift as per Lit SDK JavaScript

1. The user signs in to his Google account using a native iOS OAuthProvider component
2. Lit SDK iOS calls Lit relay server to mint a PKP using the returned credential response
3. The user gets public key and address from the minted PKP
4. Lit SDK iOS gets session signature from Lit node client iOS
5. Lit SDK iOS executes a Lit Action to construct and sign a transaction, then returns the signed raw transaction
6. Lit SDK iOS broadcasts the signed raw transaction on the blockchain (Polygon Mumbai Testnet)
7. The user is able to view the transaction on the blockchain explorer
8. We could apply daily withdrawal limit using Lit Action (nice to have)
9. We could utilize Lit relay server's built in private key in order to subsidise users for a gasless experience (nice to have)
10. Branding and UX polishing (nice to have)

### Milesone 1
1, 2, 3

`$1K, to be completed by 2023-01-13`

### Milesone 2 
4, 5

`$2K, to be completed by 2023-01-29, consider time for digging into Lit JS SDK, as well as Chinese new year 2022-01-21~01-27`

### Milesone 3
6, 7

`$1K, to be completed by 2023-02-15`

### Milesone 4
8, 9, 10

`$1K, to be completed by 2023-03-01, to be confirmed if we need to do them`

## Total Budget Requested

`$5K`

## Maintenance and Upgrade Plans

J Labs will be working with Lit Protocol to maintain and enhance the work for the long term.

# Team

## Team Members

`Leven Liu leven(at)j-labs.xyz`

## Team Website

https://j-labs.xyz

## Team code repositories

https://github.com/j-labs-xyz/Lit-Protocol-Swift-SDK-Demo-App

# Additional Information

The above steps have been proved working using Lit SDK JavaScript

1. PR and test transactions
https://github.com/LIT-Protocol/js-serverless-function-test/issues/3

2. The implementation is based on Lit Protocol projects and samples
https://github.com/j-labs-xyz/oauth-pkp-signup-example
https://github.com/j-labs-xyz/relay-server
https://github.com/j-labs-xyz/js-serverless-function-test

**Comment by debbly** [comment]
Hi @j-labs-xyz,

Milestone #1 and Milestone #2 make sense to me. I have some questions about Milestone #3 and Milestone #4. Currently, the Lit relay covers a specific case of broadcasting a transaction on chain and also covers the gas for doing so - will you be using Lit's relay server to do step 6?

**Comment by j-labs-xyz** [comment]
> Hi @j-labs-xyz,
> 
> Milestone #1 and Milestone #2 make sense to me. I have some questions about Milestone #3 and Milestone #4. Currently, the Lit relay covers a specific case of broadcasting a transaction on chain and also covers the gas for doing so - will you be using Lit's relay server to do step 6?

Hi @debbly , sure we will have a look at the way that Lit's relay server works for broadcasting, and use it for this case if applicable. Thanks for the advice.

**Comment by debbly** [comment]
Awesome, I think the structure of this grant will look like:

Milestone 1:

1. The user signs in to his Google account using a native iOS OAuthProvider component
2. Lit SDK iOS calls Lit relay server to mint a PKP using the returned credential response
3. The user gets public key and address from the minted PKP
4. Lit SDK iOS gets session signature from Lit node client iOS
5. Lit SDK iOS executes a Lit Action to construct and sign a transaction, then returns the signed raw transaction
6. Lit SDK iOS broadcasts the signed raw transaction on the blockchain (Polygon Mumbai Testnet)
7. The user is able to view the transaction on the blockchain explorer

$2.5k

Milestone 2

1. We could apply daily withdrawal limit using Lit Action (nice to have)
2. We could utilize Lit relay server's built in private key in order to subsidize users for a gasless experience (nice to have)
3. Branding and UX polishing (nice to have)

$1k

Let me know if you have any questions!

**Comment by johnnynanjiang** [comment]
The work has been done and published on GitHub

https://github.com/j-labs-xyz/lit-swift-sdk
https://github.com/j-labs-xyz/lit-wallet-example
