### ISSUE TITLE
Open Grant: Sling Protocol

### ISSUE THREAD

**Issue by Joseph-Gross** [LIT-Protocol/LitGrants#4]
# Open Grant Proposal: `Sling Protocol Grant Proposal`

**Name of Project:** Sling Protocol

**Proposal Category:** `integration-adoption`

**Proposer:** `Joseph-Gross`

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:**
Yes, but gradually over time. We intend to build a full decentralized automation network with an entire ecosystem of developers
building on top of it, so while we do intend to open source all of our work at some point, we are planning on doing so
gradually. The Lit Protocol component of our network, however, is one of the first components we intend to open source with
the MIT license.

# Project Description

We are building a decentralized and user-friendly automation network. In the long term, we envision a protocol layer
that users, developers, and enterprises can use to automate any on-chain action(s) and
compose these automations into complex transactional state machines. This is infrastructure for making highly composable
and flexible new primitives.

Sling Protocol is composed of two elements: a secure, decentralized orderbook, and a competitive network
of executors. Our SDK can be used to create programmable orders, which will be
executed upon certain condition(s) being met. Once the order object has been created, it shall be encrypted and submitted to the orderbook. Access control conditions and a symmetric key will be submitted to Lit Protocol. When an executor verifies that an
order’s condition has been met, its order data is decrypted using Lit and the executor may execute the order on chain, receiving a
reward left by the user that placed the order.

Our plan is to open-source the contracts and SDK. To facilitate adoption, we will build protocols, tools, interfaces to demonstrate the power of Sling. Some examples:

- Algorithmic Trading
- Creating a virtual orderbook on any structured product
- NFT/ENS Sniping
- Automated Liquidity Bridging
- Governance/DAO Management

The future of Sling is an established multichain hyperstructure facilitating trustless conditional transaction execution for its users. In a world where more and more software use cases and moving some component on-chain, we will enable users to
take full control over their cryptographic assets.

## Value

We believe we are building a new primitive in the blockchain ecosystem. By introducing a generalized, decentralized,
automation layer, we can enable cross chain communication, complex trading strategies, on chain hedge funds, automated
LP management, and so much work. We believe that if we get this right, Sling Protocol can be the gateway to most DeFi
protocols as well as future use cases that we haven't yet thought of. The risks that we don't get it right are a lack
of developer adoption, a lack of consumer adoption, and ultimately, it will mean that the protocol we spent months and
maybe years building was unable to reach a high level of adoption.

The major risks we have identified for this project are developer adoption, UI / UX design and optimization, and prioritizing
our time on the right use cases. We see our protocol as having a very wide range of use cases, but our team is currently
very small, so finding the right use cases to hone in on and prioritize in these early stages will be extremely important.
The primary difficulty of this project comes from the massive scope of what's possible as well as the technical and regulatory challenges that come with
designing a distributed network.

## Deliverables

We see what we're building as an evolving ecosystem
to power the next wave of decentralized applications. At the infrastructure level, the first version of our network will have a decentralized private storage system (using Lit + IPFS), a network of executor bots, and deployed protocol contracts.

Once this is done we will get to work building sub-protocols, all created by the team, that use Sling's functionality. This serves to encourage development on Sling and also orgranically grow the volume of order executions on our network. These projects will likely look like the use-cases described above but as more innovative protocols come out and gain traction we will have a steady supply of new use-cases to focus on.

## Development Roadmap

Note that these milestones are not sequential and we will be working on multiple tasks asynchronously depending on our bandwidth.

Milestone 1: Distributed Orderbook (secure, trust-less, encrypted)
- Timeline: 3 months
- Cost: $5,000
- Developer: Joseph Gross
- Description: The core infrastructure for our network. This is a layer that is heavily integrated with Lit Protocol and is built on
  IPFS. Our storage layer will be completely secure and using lit protocol to encrypt orders, it will also be private.

Milestone 2: Orderbook Explorer
- Timeline: 2 weeks
- Cost: $1,000
- Developer: Nick Ciepley
- Description: A very basic UI for monitoring your orderbook in real time. This can also be applied to monitor an executor's progress
  in processing transaction in real time

Milestone 3: Executor Network
- Timeline: 2 months
- Cost: $4,000
- Developer: Joseph Gross
- Description: A network of at least 5 executor nodes working to process transactions for the network. The goal is for there to
  always be at least 5 executor nodes running at any given point in time. These will initially be run by the team, but
  we plan on developing an executor marketplace where developers can license their executors for a share of profits. We
  also plan on releasing developer tools for writing your own executor that follows our framework.

Milestone 4: Core SDK
- Timeline: 4 months
- Cost: $10,000
- Developer: Joseph Gross
- Description: Our core sdk should be completed. This included the common module, storage module, and order module. While this will
  initially be closed source and used for internal development, we intend to use this sdk to build higher level abstractions
  and wrappers for different use cases using the sdk. Eventually, we plan on fully open sourcing our sdk.

Milestone 5: Audited Smart Contract Layer
- Timeline: 4 months
- Cost: $20,000
- Developer: Richter Brzeski & Joseph Gross
- Description: All of our smart contracts audited and deployed on at least 5 EVM compatible chains

Milestone 6: Developer SDK v1
- Timeline: 1 month
- Cost: $3,000
- Developer: Richter Brzeski & Joseph Gross
- Description: The first version of the sdk we will released for developers to build dApps using Sling Protocol

Milestone 7: Proxy Account Portfolio Page
- Timeline: 2 weeks
- Cost: $1,000
- Developer: Joseph Gross & Will Seiple
- Description: Basic UI for connecting your wallet and interacting with all of your authorized Sling Proxy accounts

Milestone 8: Sling dApp Component Library
- Timeline: 2 weeks
- Cost: $1,000
- Developer: Nick Ciepley & Will Seiple
- Description: A basic component library for building Sling dApps. We envision a similar toolset to the one provided by Gnosis Safe

Milestone 9: UI / UX Design System
- Timeline: 1 month
- Cost: $5000
- Developer: Outsource to product design agency or hire contracted designer
- Description: Create a comprehensive design system in line with our mission and brand.

## Total Budget Requested

Total: $50,000

We are expecting to allocate a vast majority of our budget to salary and operational expenses. We don't currently have any
other overhead besides salaries and team expansion. However, depending on other funding leads that we are currently
pursuing, we may outsource or hire UI / UX talent to help develop our brand as well as a comprehensive user experience
and Sling design system. It is also important to note that we have been working since January so many of the deliverables
above have already been started in some capacity.

## Maintenance and Upgrade Plans

We currently have 4 full time developers and intend on working full time throughout the summer. Though we are also planning
on returning to school, we will continue working on Sling Protocol (reduced hours in the Fall). However, depending on
our funding situation by the end of the summer, we will decide on whether to expand the team by hiring a full time developer,
biz dev guy, or marketing / branding / UI and UX designer. We believe we can launch a functioning beta version of our
ecosystem (i.e. the milestones listed above) by the end of the summer, and then continue to maintain, innovate, and develop
new features throughout the rest of the year. It is also important to not that 3/4 team members will be graduating in a
year and we all plan on continuing with Sling Protocol full time in between semesters (which for us in December - February).

# Team

## Team Members (and Linkedin Profiles)

[Richter Brzeski](https://www.linkedin.com/in/r-brzeski/)

[Joseph Gross](https://www.linkedin.com/in/josgross/)

[Will Seiple](https://www.linkedin.com/in/wseiple/)

[Nick Ciepley](https://linkedin.com/in/nicholas-ciepley)

## Team Website

[Sling Protocol (landing page)](https://slingprotocol.xyz)

## Relevant Experience

Richter Brzeski

- EECS @ MIT
- CTO @ Ambo
- Software Developer @ MyCrypto
- Smart Contract developer for Rari Capital
- Software developer @ Apple

Joseph Gross

- EECS @ MIT
- Software Developer @ Flytrex
- Software Developer @ DeepBlocks

Will Seiple

- Math & CS @ MIT
- Software Developer @ IDMission
- Analyst @ Ramiel Capital (Crypto Hedge Fund)

Nick Ciepley

- Aerospace Engineering & CS @ MIT
- Software Developer @ Viasat Inc.

## Team code repositories

Though we intend to open source certain SDKs, our smart contracts, and executor bots at a certain point, we are still
currently working towards a Beta version of our protocol, and as a result, are still closed source. However, we are happy
to go over our code base while on a call or in person (we will be at EthNYC from Jun 24-26). Additionally, most of our
personal GitHub have proprietary work.

GitHub Links:

- [Sling Protocol Team GitHub](https://github.com/Sling-Protocol)
- [Richter's GitHub](https://github.com/richtermb)
- [Joseph's GitHub](https://github.com/Joseph-Gross)

# Additional Information

We met with David in person at Consensus 2022 in Austin. He told us about the grant program and encouraged us to apply.

Contact Info:

- Email: joseph@sling.space
- Telegram: @joseph_gross

**Comment by debbly** [comment]
Hi @Joseph-Gross, David followed up with y'all in person about this grant. We'd love to work with y'all and figure out how we can get some funding for your project. 

Please update the proposal scoped for how the team will be using Lit Protocol!

**Comment by Joseph-Gross** [comment]
## Development Roadmap









Milestone 1: Distributed Network of Orderbooks (secure, trust-less, encrypted)
- Timeline: 3 months
- Cost: $5,000
- Developer: Joseph Gross
- Description: The core infrastructure for our network. This is a layer that is heavily integrated with Lit Protocol and is built on
  IPFS. Our storage layer will be completely secure and using lit protocol to encrypt orders, it will also be private.
- Lit Protocol Integration Level: Essential (i.e. In order to successfully utilize a decentralized storage provider, we require lit protocol's conditional encryption capabilities to secure our user's data).

Milestone 2: Personal Orderbook Explorer
- Timeline: 2 weeks
- Cost: $1,000
- Developer: Joseph Gross & Nick Ciepley
- Description: An interface for monitoring the status of your orders in real time. This component integrates heavily with Lit Protocol in order to decrypt open orders and display the order metadata.
- Lit Protocol Integration Level: High (i.e. this component will not be effective if we do not have lit protocol integration to decrypt the orders)

Milestone 3: Executor Network
- Timeline: 2 months
- Cost: $4,000
- Developer: Joseph Gross
- Description: A network of at least 5 executor nodes working to process transactions for the network. The goal is for there to
  always be at least 5 executor nodes running at any given point in time. These will initially be run by the team, but
  we plan on developing an executor marketplace where developers can license their executors for a share of profits. We
  also plan on releasing developer tools for writing your own executor that follows our framework. This component utilizes lit by constantly scanning the orderbook for pre-conditions that are valid. If an order's conditions are found to be valid, the executor connects to Lit Protocol in order to decrypt the full order object and submit the order on-chain.
- Lit Protocol Integration Level: Essential (i.e. this component does not work without Lit Protocol to decrypt the order object)

Milestone 4: Core SDK
- Timeline: 4 months
- Cost: $10,000
- Developer: Joseph Gross
- Description: Our core sdk is the main module for interacting with our system's infrastructure from an external perspective (i.e. building on top of sling). This included the common module, storage module, and order module. While this will initially be closed source and used for internal development, we intend to use this sdk to build higher level abstractions and wrappers for different use cases using the sdk. Eventually, we plan on fully open sourcing our sdk. It is important to note that our sdk will naturally contain tools for building on top of lit protocol but will be abstracted by higher level methods such as `encrypt(order: SlingOrder, signer: Signer)` and `decrypt(order: EncryptedOrder, signer: Signer)`. While this component does not implement any novel lit protocol integration not previously detailed in milestones 1-3, it builds heavily on the work detailed above and includes building out various abstractions / tools for utilizing lit protocol.
- Lit Protocol Integration Level: High

Milestone 5: PKP Exploration and integration
- Timeline: 2 months
- Cost: $0
- Developer: Joseph Gross & Richter Brzeski
- Description: We believe PKPs have huge potential and as a result, are intending to look into them heavily for integration into our protocol. The reason why this deliverable does not have an explicit cost is because while we are certainly going to spend time researching and ideating on PKPs, the actual product of their integration will most likely fit within milestones 1-3. One of the ideas that we have begun exploring is the application of PKPs as an alternative to our proxy contract model in order to reduce gas fee overhead of interacting with our protocol.

## Total Budget Requested



Total: $20,000

We are expecting to allocate a vast majority of our budget to salary and living expenses. We don't currently have any
other overhead besides salaries and team expansion. However, depending on other funding leads that we are currently
pursuing, we may outsource or hire UI / UX talent to help develop our brand as well as a comprehensive user experience
and Sling design system. It is also important to note that we have been working since January so many of the deliverables
above have already been started in some capacity. I want to emphasize that Lit Protocol is essential to our mission of maintaining a decentralized, secure, and private network of orders books. Without Lit Protocol, we would be required to either centralize our server or make all order books private.

**Comment by debbly** [comment]
Awesome. We really enjoyed reading through your project proposal and would like to fund milestones 1 and 2, then revisit funding for additional milestones as they get closer. Look out for an email to submit payment information!

**Comment by Joseph-Gross** [comment]
Hey had a chat with the lit team. Actually we’re gonna do the following:

1. Build a PKP DEX SDK for calling common functions
- Mint a new liquidity position
- Add liquidity to existing position
- Remove liquidity from an existing position
- Swap token A for token B

2. Build an explorer / utils for Lit Actions 
- Interface that allows for easy interaction with existing Lit Actions and creating new Lit Actions
- Begin thinking about what a lit action marketplace / registry would look like (similar to ceramic data model composability)

3. Build an explorer / utils for PKPs
- Interface that allows for easy interaction with PKPs you own and creating of new PKPs
- Begin thinking about what a dedicated PKP marketplace would look like 

4. Begin ideating how to integrate a generalized execution network with Lit Protocol (i.e. PKPs, access control conditions, Lit Actions, and more)

5. Propose a PKP + Lit Action Automation SDK
- Ideate what an automation ecosystem would look like with Lit Actions + PKPs
- Put together a detailed proposal with a development roadmap for the tooling + interfaces for automating DeFi interactions using PKPs, a generalized automation network, and lit actions
