### ISSUE TITLE
Small Grants: <Your Title Here>

### ISSUE THREAD

**Issue by nas** [LIT-Protocol/LitGrants#43]
### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Lit Protocol prizes? Include links here if available:

### 7. Total Budget Requested
* Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our grant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal, OpenSea)
  * Please link to your submission

**Comment by debbly** [comment]
Hi @nas! Please fill in the relevant fields with information about your grant proposal! 

Looking forward to reviewing it :)
