### ISSUE TITLE
Small Grants: <Your Title Here>

### ISSUE THREAD

**Issue by lorenzoshoenleber** [LIT-Protocol/LitGrants#48]
### 1. What is your project? (max 100 words)

Our project seeks to fill the gap in academic literature and knowledge about impermanent loss, a major risk in DeFi while offering solutions for investors to hedge and reduce this risk. With two main contributions, we aim to provide valuable insights and strategies to help DeFi investors efficiently navigate and minimize impermanent loss. 

First, we develop a continuous-time stochastic model to explain impermanent loss dynamics in liquidity pools. By calibrating the model to real-world data, we analyze the risks faced by investors. Preliminary findings suggest that the impermanent loss is influenced by token return volatilities and their correlation.

Second, we focus on hedging impermanent loss by utilizing stochastic control theory. Through a portfolio problem, we aim to minimize one-step-ahead impermanent loss for yield farmers. The optimal strategy will determine the best holdings in the underlying token pair outside the pool or derivatives such as call or put options.

### 2. How is Lit used for this project? (max 100 words)
 
The stability and efficiency of financial markets heavily rely on the crucial significance of liquidity. You would sponsor a high-level academic research paper in DeFi and hence gain visibility among the academic community. Our current paper “Maneuvering and Investing in Yield Farms” (https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4422213) got presented already at various conferences. Besides the visibility, the results which we provide in our paper can be useful for the enhancement and development of the current architecture of your dApp. For example, via a simulation study, one could provide corridors for the expected impermanent loss. Besides, the paper would guide and educate the investor on how to avoid or hedge impermanent loss. 

In addition, we just held a one-day conference by the Collegio Carlo Alberto and the University of Turin, called [ToDeFi](https://www.carloalberto.org/event/todefi-torino-decentralized-finance-conference/): Torino Decentralized Finance Conference 2023 (https://www.carloalberto.org/event/todefi-torino-decentralized-finance-conference/), which promoted the highest level and up-to-date research in DeFi within the academic community. Speakers and discussants were selected among the most innovative junior researchers and established scholars. We are planning to make the conference a yearly event. Beyond the research support, we are potentially open to discuss about a deeper cooperation. In particular, the Collegio Carlo Alberto hosts a postgraduate Master’s in finance, insurance, and risk management (Mafirm), which is a small high-quality program that exists for more than 20 years. The program appears in several international rankings (e.g., 1st in Italy, 6th in Europe, and 25th worldwide in the quantitative finance masters' ranking by Risk.net). The students attending our master lectures are excellent but more importantly, really motivated.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The grant would bring us one step closer to carrying out the proposed research project. We would spend the grant for acquiring the respective datasets, the hardware for the computation, and for hiring a well suited student from the University. 

We aim for the successful completion of the academic paper and its subsequent publication in a reputable journal. The publication demonstrates that the research was conducted effectively and contributes to the academic community. In addition, the impact of the paper can be measured by the number of citations which suggests that the research has been influential and has generated interest within the academic community. Success can also be evaluated based on the opportunities for collaborations and networking that arise from the research (such as our yearly conference ToDeFi). If the grant helps establish connections with other researchers, institutions, or organizations, it can enhance the visibility and impact of the work. In addition, we are aim for research which is practically applicable having a real-world impact. If the findings of the paper are implemented in practice or contribute to solving real-world problems, it demonstrates the relevance and value of the research.
 
### 4. Is this project open source?
NA

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Yes

### 6. Links and submissions

https://sites.google.com/view/lorenzo-schoenleber/menu
https://math.sciences.ncsu.edu/people/apapani/
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4422213
https://www.carloalberto.org/event/todefi-torino-decentralized-finance-conference/
https://www.carloalberto.org/education/master-in-finance/

### 7. Total Budget Requested

In order to implement our optimization framework, we have to model the underlying relevant stochastic processes: While current spot prices are publicly available, dedicated firms such as https://tardis.dev/ offer access to various cryptocurrency derivative trading platforms, which we need to acquire for this project. Pool data can be sourced for free via The Graph as done in our current project. On top of the data acquisition, we need to hire a Research Assistant, who helps us to access and analyze the relevant data. The optimization framework requires high-level hardware and computing capabilities which we need to acquire (or rent) for this project.

The price for the Tardis API for 1 year is about 6.000€. Hiring a Research Assistant for about 1.5 years accumulates to approximately 8000€. Hardware can be acquired for less than 2000€. 

We want to emphasize that any amount of sponsorship or donation would be beneficial for us since we are trying to request funding from different funding sources to realize this project.
  
### Additional questions:

Prof. Dr. Lorenzo Schoenleber is an Assistant Professor in Finance at the Collegio Carlo Alberto and the University of Turin. He obtained his PhD at the Frankfurt School of Finance. He is also associated with the Fintech & Digital Finance Chair at Paris Dauphine University. His area of specialization is empirical asset pricing (option-implied information) and DeFi (Yield Farming). 

Prof. Dr. Andrew Papanicolaou is an associate professor in the Department of Mathematics at North Carolina State University (NCSU). His PhD is in applied mathematics from Brown University. His research interests are computational finance and stochastic systems for control and optimization. The applications of this work include financial data analysis and the challenges associated with these highly complex data sets. My background is in probability theory and nonlinear filtering. 

Dr. Siddharth Naik is a quantitative portfolio manager and trader with over 7 years of experience at institutional hedge funds (systematic macro and low latency, respectively) with extensive experience in trading fx, futures, and crypto instruments. He has previously published multiple papers on non-convex optimization mechanism design and trading crypto since 2017. Previously he was a CEO at RadioLytics a startup, which aimed at making spectrum tradable.
[IL_pitch_deck.pdf](https://github.com/LIT-Protocol/LitGrants/files/11479041/IL_pitch_deck.pdf)

**Comment by debbly** [comment]
Hi @lorenzoshoenleber - we only fund open source tooling that extends the use of Lit Actions and Programmable Key Pairs. This grant does not qualify. Please reopen an issue if there are any updates!
