### ISSUE TITLE
Open Grant: iris

### ISSUE THREAD

**Issue by Victoriakim** [LIT-Protocol/LitGrants#5]
# Open Grant Proposal: `iris`

**Name of Project:**

**Proposal Category:** Choose one of  `integration-adoption` 

**Proposer:** Victoriakim

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

We're building a social platform for web3 communities on top of Lens protocol, a social graph and a composable backend with modularized functionalities. The future of web3 social media is around the corner, thousands of protocols are being built to tackle governance, moderation, and monetization -however, there is one big opportunity that is lacking: an application layer that utilizes the right technology to deliver an amazing low friction user experience. 

On top of this, we recognize the need for community-based social platforms, to handle everything from scoping community health and sentiments, to engaging in conversation. iris will be a medium for DAOs and NFT project communities to share their thoughts and content both exclusively to their own people, and publically.

i.e. imagine a future where gated discussions around snapshot proposals can happen on iris and members can "Like" comments they agree and freely express their opinions. 

While there is yet to be a permission layer built on Lens, we believe we can build this by integrating Lit Protocol. Our team has already completed a first iteration of this integration on our testnet (testnet.irisapp.xyz), where an individual has the ability to create a post publically or privately only to their followers. In the future we plan build this out further to onboard whole communities, and be able to gate access to content based on token holders of specific NFTs. 

We believe a platform like iris can enable communities to undergo more streamlined conversations, express sentiments, and cultivate a collective spirit. 

## Value

If iris becomes wildly successful it will be mutually beneficial for Lit Protocol as so many people will be able to see the power of Lit's access control and encryption abilities. Gated content is an amazing non-abstract method of understanding what Lit does, and we believe the greater experiences we can build off of Lit's protocol, the more adoption it'll bring into the Lit ecosystem. 

Even in the scenario we don't get it right, we think all the data in understanding why or how it didn't work out will be valuable for Lit to continue building out their protocol. The stakes are also low, because Lens itself is a very early-adopter demographic, there is more leniency with experiments and projects. 

## Deliverables

App launched on mainnet built ontop of Lens and deployed on Polygon, that can gate content based on a the tokens that a user holds and that supports experience for community content. 

## Development Roadmap

**Phase 1: Public and Private posts on Mainnet** 
- Feature description: Ability to post private content to your followers only and set custom follower fee 
- Technical implication: Integrate Lit Protocol to interact with mainnet app in production and set up the Lens follow module 
- This would be a developers front-heavy milestone to set up the technical backend. Once completed designers should create new hifi-s to differentiate public and private posts.
- ETA: July 22nd
- Funding Required: 3000 USD

**Phase 2: Community-based gating** 
- Feature description: Ability to gate content by token holders and build feeds catered for your specific communities 
- Technical implication: Integrate Lit Protocol to decrypt based on token 
- -> Create UX workflow for community content 
- -> Build out algorithm for community based feeds 
- -> New designs for feeds 
- -> Implementing Lit Protocol further and updating frontend 
- -> Launching on Twitter and selectively onboarding our first community 
- ETA: September 30th
- Funding Required: 7000 USD

## Total Budget Requested: 10000 USD

Engineering Labour (5000 USD)
Design Labour (3000 USD)
PM and Community Labour (1000 USD)
Research and fixed costs (i.e. figma, webflow subscriptions) (1000 USD)

## Maintenance and Upgrade Plans
We're a group of ambitious builders who love to build, create, and iterate. We will continue working on iris as a special passion project. 

# Team

## Team Members

Ian Mah, Developer
Isaac Chung, Developer
Vandy Liu, Developer
Novia Chao, Designer
Austin Leung, Designer
Victoria Kim, PM

## Team Member LinkedIn Profiles

[[Ian Mah - The University of British Columbia - Vancouver, British Columbia, Canada | LinkedIn](https://www.linkedin.com/in/ianmah/)](https://www.linkedin.com/in/ianmah/)

[[Vandy Liu - Greater Vancouver Metropolitan Area | Professional Profile | LinkedIn](https://www.linkedin.com/in/vandy-liu/)](https://www.linkedin.com/in/vandy-liu/)

[[Isaac Chung - Software Engineer Intern - Tesla | LinkedIn](https://www.linkedin.com/in/isaac-chung-08/)](https://www.linkedin.com/in/isaac-chung-08/)

[[Novia Chao - Product Design Intern - Benevity | LinkedIn](https://www.linkedin.com/in/noviachao/)](https://www.linkedin.com/in/noviachao/)

[[Victoria Kim - Founding Product Marketing Manager - Utopia Labs | LinkedIn](https://www.linkedin.com/in/victoriasekim/)](https://www.linkedin.com/in/victoriasekim/)

## Team Website
https://www.iris.social/

## Relevant Experience
As a team we've won 3 ETH Global Hackathons, Iris (https://showcase.ethglobal.com/lfgrow/iris-bnw7a), Tempra (https://showcase.ethglobal.com/ethamsterdam/tempra-xnxf4), and Reverb (https://showcase.ethglobal.com/ethnewyork2022/reverb-x2kgs)

## Team code repositories
https://github.com/ianmah/tempra
https://github.com/ianmah/reverb

# Additional Information

David told us about it!

victoriakim048@gmail.com

**Comment by debbly** [comment]
Hi @Victoriakim, this project is great!

Currently, we're focusing on funding projects that are building open source tooling with Lit Protocol - that might look like an integration tool or library. If y'all want to update your proposal to what that specifically might look like for your project, please do! Otherwise, the scope of the project is not what we are looking to fund at the moment.
