### ISSUE TITLE
Open Grant: Bitbars

### ISSUE THREAD

**Issue by MuffinsThaCat** [LIT-Protocol/LitGrants#50]
# Open Grant Proposal: Bitbars

**Name of Project:** Bitbars

**Proposal Category:** Choose one of `app-dev`, `integration-adoption` , `technical-design`, `docs` , `research`   Learn what these categories are here: {https://github.com/LIT-Protocol/LitGrants/tree/main/open-grants}"

app-dev

**Proposer:**  MuffinsThaCat

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"

Yes

# Project Description

The goal of Bitbars is to take up as much blockspace as possible. We store 1kb on the Bitcoin blockchain and mint an ordinal with an image of a 1kb bar. 
Here is an example: https://openordex.org/inscription?number=38689

Please describe exactly what you are planning to build. Make sure to include the following: -

The problem we are trying to address is the lack of utility in inscriptions of Ordinals on BTC for cross-chain applications. We would like to see the utility first expand to being able to sell them on Ethereum using OpenSea as the marketplace.
We want to build an application using PKPs for Ordinals on Bitcoin in cross-chain applications. Starting with the use case of a user being able to send a mix of BTC and ETH currencies and/or NFTs to their PKP, and then sell it as a bundle by selling the NFT that controls it on OpenSea. The buyer would then be able to withdraw or utilise the assets contained therein as they desire.
Per: https://litprotocol.notion.site/Lit-Request-for-Ecosystem-Proposals-ae3f31e7f32c413cbe0b36c2fe53378d?p=f19bce1094404418b10090103fc576fc&pm=s

## Value

We have minted ~1k of these within the first 100k ordinal inscriptions on Bitcoin, and several thousands more thereafter. We have also begun minting Ordinals and Litecoin which we have thought to appropriately name Litbars :). 

 Performative application that we will maintain built onto the Lit Protocol. A lot of stored up value in the already minted Bitbars. 
 We've discovered a lack of market opportunity for trading Ordinals anywhere other than the chain they were minted. 
 Mixing understanding of how to build the application with how Lit Protocol, Actions work.

## Deliverables

Basic Front End
Ability to mint a new PKP
Ability to create a PKP as an NFT
Ability to send and receive from a Bitcoin and Ethereum wallet with the PKP as an NFT 

## Development Roadmap

We will make use of some of the functionality provided for by the SDK developed by Yacht Labs. 
Per: https://github.com/Yacht-Labs/yacht-lit-sdk (big thanks to them for laying the groundwork)

We will replicate the methods to be able to mint a PKP and create a (PKP) NFT which can be at first used to access, send and receive from a Bitcoin, Ethereum and Stacks Wallet.      1000.      2 people

We will use a DID provider with integrated Lit Actions x PKP powered by Lit Protocol for did:key using secp256k1 so that Lit Actions can use PKPs to sign transactions.
Instead of manually providing a PUBLIC_KEY to get the DID (decentralised identifier), we get the PUBLIC_KEY from the PKP NFT
The DID is passed into a resolver to allow us to run methods such as did.authenticate().
To authenticate, instead of providing a PRIVATE_KEY to sign a message to verify the signature from the signed message matches the corresponding PUBLIC_KEY, we will ask the Lit nodes, who hold the PRIVATE_KEY collectively of the PKP NFT, to execute some static Javascript code that is hosted on IPFS and use the output signature to verify.
So now that PKP NFT owns the decentralised identifier DID, we can use this DID to send and receive from a wallet that only this PKP NFT owner can do.
Per: https://github.com/LIT-Protocol/key-did-provider-secp256k1.    1000.  2 people

We will need to include this all in a client-side web application with basic front end to be able to access.  500.   2 people

## Total Budget Requested

2500 spent on the time it will take for us to develop it

## Maintenance and Upgrade Plans

We will want to develop signing methods for P2TR into the SDK created by Yacht Labs in the future
Maintenance of this early stage of the project will be done as needed as we expand the scope of functionality we want to use on Bitcoin, Ethereum and Stacks

# Team

## Team Members

Antoine De Vuyst
Tal Zisckind

## Team Member LinkedIn Profiles

https://ca.linkedin.com/in/antoine-de-vuyst-49a74194
https://ca.linkedin.com/in/tal-zisckind-b72367a0

## Team Website

https://devcash.dev

## Relevant Experience

Antoine - Very early into Bitcoin and Ethereum, understands the core ethos of their communities. Javascript and Solidity
Tal - Core developer on formerly prominent fork of Bitcoin(Metaverse ETP) Javascript, Typescript, Solidity and Rust

## Team code repositories

https://github.com/blockdevsunited

# Additional Information
Blockworks Grant
talzisckind19@gmail.com

**Comment by debbly** [comment]
hey @MuffinsThaCat, thanks for submitting a grant - 

Could you explain more on how you plan to utilize PKPs and what application you are building?

from the deliverable section 
```
Basic Front End
Ability to mint a new PKP
Ability to create a PKP as an NFT
Ability to send and receive from a Bitcoin and Ethereum wallet with the PKP as an NFT
```

The PKP is an NFT in the form of an ERC-721. Do you mean creating another NFT that the PKP holds?

For the last point, Yacht labs has laid the foundation to receive and send bitcoin with the PKP, how is your application different or extending that use case?

**Comment by MuffinsThaCat** [comment]
hi @debbly 

Sorry I double spoke in saying the ability to create a PKP as an NFT. Nothing so complicated.

Our goal is to create an application that we and eventually anyone can use to send and receive to and from an address which uses a PKP for signing. The PKP can then be sold on OpenSea. So we need a way to show which addresses are controlled by the PKP and what they hold. So that if someone purchases the PKP on OpenSea they can go to our application to manage what's inside. 

I would only call the project different in what it will attempt to do in the future. We do not want to do swaps in the future, we want to create Lit Actions which use Ordinals to execute transactions over other blockchains. If you have Bitbar x, you can perform action y. It would be folly to go into more detail beyond that. Not until that x is something valuable that compels people to buy and hold, and that y is an action they would not be able to otherwise have, access or do so easily. Until then it'll be selling Bitbars with 42690 BARS(token on ethereum) in a bundle as a PKP on OpenSea. And the application we build will allow us to do this.

on second thought: one almost obvious use case of having x to do y, is token gating(say with 10 or 10kb in Bitbars) use of an application that has the ability to efficiently set up the same campaign. However, I might prefer more ambitious avenues which use P2TR to lock an Ordinal on Bitcoin and mint or borrow on another chain.

**Comment by debbly** [comment]
@MuffinsThaCat we will not be moving forward with this grant. If you have questions, please reach out to @davidlsneider (david@litprotocol.com).

**Comment by debbly** [comment]
@MuffinsThaCat we will not be moving forward with this grant. If you have questions, please reach out to @davidlsneider ([david@litprotocol.com](mailto:david@litprotocol.com)).
