### ISSUE TITLE
Open Grant: DAOsign

### ISSUE THREAD

**Issue by TetianaRiabova** [LIT-Protocol/LitGrants#54]
# Open Grant Proposal: `DAOsign`

**Name of Project:** DAOsign

**Proposal Category:** `metaverse`

**Proposer:** `TetianaRiabova`

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

DAOsign is a decentralized platform for agreements and automated workflows, with publicly verifiable, cryptographic proofs-of-signature, designed for DAOs and WEB3 companies.
Verifiable Signature is at the core of DAOsign and is based on 3 key proofs: proof-of-identify, proof-of-authority, and proof-of-agreement. Utilizing these proofs, DAOsign provides a platform to design and configure complex workflows that combine smart-contract-based automation with authorized approvals.
**Problem, that we solve:**
Traditional methods of signing agreements, such as paper-based systems or legacy e-signatures, are prone to fraud and lack transparency and offer no solution for verifying the signer's identity or authority to execute the agreement. Instead, these systems rely on costly legal proceedings to enforce agreements.
**Our solution:**
DAOsign combines proof-of-agreement, proof-of-signature, and proof of authority into a publicly verifiable cryptographic proof enabling secure, transparent, and automated processing of complex agreements and smart contracts.
![image](https://github.com/LIT-Protocol/LitGrants/assets/122782612/d01c876e-80dd-4701-bb2c-671af80c5b69)

## Value

Getting this proposal right would be highly valuable for the Lit ecosystem. DAOsign would enhance functionality, improve governance, increase adoption, ensure cross-platform compatibility, and boost community participation. These advantages contribute to the overall growth and success of the Lit ecosystem, creating a more efficient and sustainable environment for decentralized collaboration and innovation.

We have prepared a risk mitigation plan that includes technical, legal and scalability risks but currently there are no red flags that might stop us from delivering the grant scope in time.

## Deliverables

The final deliverable for this project will be **a fully functional and user-friendly agreement-signing tool for DAOs and web3 companies.** The software will provide a secure and decentralized platform for stakeholders to create, sign, and execute agreements in a transparent and tamper-proof manner. The tool will be designed to work seamlessly with various blockchain networks, ensuring cross-platform compatibility and broad adoption within the web3 ecosystem.

## Development Roadmap

Blockchain Integration - Q3 2023 - $25 000
Snapshot + GPT3 Integration - Q3 2023 - $10 000 
Agreement Invoicing - Q4 2023 - $10 000
Plugins Marketplace and Tokenization - Q4 2023 - $5 000

## Total Budget Requested

$50 000

## Maintenance and Upgrade Plans

Our team is committed to the long-term maintenance and continuous improvement of DAOsign. And our plans include:

- Ongoing Support. We will provide regular updates and technical support to address any issues or bugs that may arise.
- Collaboration with the Community. As was mentioned above we're planning the launch Early Adopters Program, and gathering feedback, which will lead to the improvement of our tool and its functions. Also, we will actively engage with the community through social media, and community events to gather insights and incorporate valuable feedback into our development roadmap.
- Integration with Ecosystem Updates. Closely monitoring updates within the Lit ecosystem, we want to ensure seamless integration with any protocol upgrades or changes.

# Team

## Team Members

Eugene Fine - CEO & Founder
Ramil Amerzyanov - CTO
Misha Kushka - Technical Lead
Oleksandra Burmenska - Business Development Director

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/eugenefine/
https://www.linkedin.com/in/ramil-amerzyanov/
https://www.linkedin.com/in/mkushka/
https://www.linkedin.com/in/oleksandra-burmenska/

## Team Website

https://daosign.org/

## Relevant Experience

Eugene Fine (CEO & Founder) - Former CTO for ExplorerSurgical, VP of Engineering at [GHX North America](https://www.ghx.com/digital-case-support/), tech advisor for [Polywrap.io](https://polywrap.io/#/).
CEO for [DAOsign](https://daosign.org/), [CIDT](https://consideritdone.tech/).

Ramil Amerzynov (CTO) - 15+ years in building complex enterprise solutions, a contributor to ETH and COSMOS ecosystems.
CTO for [DAOsign](https://daosign.org/), [CIDT](https://consideritdone.tech/).

Misha Kushka (Technical Lead) - Blockchain expert with a solid tech background. Winner of Blockchain hackathons. Contributor to Tier1blockchains.

Oleksandra Burmenska (Business Development Director) - Blockchain advisor with a tech background. Contributed to NEAR, Polywrap, Axelar, GnosisSafe, and Avalanche ecosystems.

Please, take a look at our portfolio with previous projects: https://docsend.com/view/fjrvjtyzgm7wgrkj

## Team code repositories

https://github.com/DAOsign

https://github.com/ConsiderItDone

# Additional Information

Please, take a look at our pitch deck with more details: https://docsend.com/view/sbexkxn5su3ahdg8

Email: sandra@daosign.org

**Comment by debbly** [comment]
Hi @TetianaRiabova, 

At this time, we only fund open source tooling that extends the use of Lit Protocol. This grant is to fund your application and does not include specifics of how you intend to integrate Lit. 

You may open a new grant with a Lit specific integration + plan for open source tooling, I'll be closing this issue for now!

Thanks,
Deb
