### ISSUE TITLE
Open Grant: Vue3Lit

### ISSUE THREAD

**Issue by NftTopBest** [LIT-Protocol/LitGrants#6]
# Open Grant Proposal: `Vue3Lit`

**Name of Project:** Vue3Lit

**Proposal Category:** `integration-adoption`

**Proposer:** `NftTopBest`

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes` 

# Project Description

Create a Vue3 component that helps other vue3 developers to integrate LIT easily.

It will provide some API or component that help developers easier to use LIT by some lines of code and with power full features in their applications.

## Value

**Benefits:** Vue3 developers can use LIT easier and with more useful features in their applications.
**Risks 1:** No vue3 developers want to use it?
**Risks 2:** I think no risk to write the vue3 compoent/package that I am a senior vue3 developer and use vue3 && LIT in my hackathon project and win some prize ;)

## Deliverables

* Vue3 developers can add a LIT control filter for their vue3 applications.
* Users can select which chain to query for the conditions below。
* Users can add ETH, ERC20, ERC721, ERC777, and ERC1155 token filters with contract address, comparators (<,<=, =, >=, >), and number
* All of the conditions can be Intersection or Union
* User hit the Calculate with LIT button will trigger a query with LIT and also show the calculated result for each condition and the final result
* Will add more features after the first version of the package publish and get feedback from developers ;)

### Milestone 1: Vue3Lit package published with version 0.1.0

* Timeline: 3 months
* Cost: $10,000
* Developer: Bruce
* Description: 
  * Vue3 developers can add a LIT control filter for their vue3 applications.
  * Users can select which chain to query for the conditions below。
  * Users can add ETH, ERC20, ERC721, ERC777, and ERC1155 token filters with contract address, comparators (<,<=, =, >=, >), and number
  * All of the conditions can be Intersection or Union
  * User hit the Calculate with LIT button will trigger a query with LIT and also show the calculated result for each condition and the final result
  
### Milestone 2:  Marketing and Maintaining issue feedback or PR for this package

* Timeline: At least 9 months
* Cost: $10,000
* Developer: Bruce
* Description: 
  * Writing a blog post in English and Chinese for this Vue3 package.
  * Publish the blog post to as many tech forums or blogging platforms as I can.
  * Maintaining issue feedback or PR for this package.
  * Create discord server to connect with package users
  
## Total Budget Requested: $20,000

All the budget will use to support my work on the vue3 package for at least 1 year(As 1 year later the package may be already stable and not much work and upgrade for it anymore).

## Maintenance and Upgrade Plans

Will maintain it for at least 1 year, but after 1 year maybe not much work then.

# Team

## Team Members

Bruce: https://github.com/NftTopBest

## Team Member LinkedIn Profiles
I don't use LinkedIn much, as all my coding work is on GitHub.

Bruce: https://github.com/NftTopBest

## Team Website

Check out my GitHub that including a lot of vue3 code develop every day;) 
https://github.com/NftTopBest

## Team code repositories

https://github.com/NftTopBest

# Additional Information
I find LIT via ETH-ShangHai

https://gitcoin.co/issue/xmtp-labs/ethshanghai-2022/1/100028887
https://gitcoin.co/issue/28892

And then know the grant program via Twitter: https://twitter.com/LitProtocol/status/1537806877211471872

**Comment by debbly** [comment]
Closing this for now as we haven't seen a demand for Vue specific integrations with Lit. Thank you for applying and we hope to see projects from you in the future.
