### ISSUE TITLE
Small Grants: ON-Chain Option

### ISSUE THREAD

**Issue by lorenzoshoenleber** [LIT-Protocol/LitGrants#62]
# On-Chain Options
_Lorenzo Schoenleber, Andrew Papanicolaou, Siddharth Naik, Andrea Andolfatto_
[On_Chain_Options_Proposal.pdf](https://github.com/opynfinance/OGP/files/12549242/On_Chain_Options_Proposal.pdf)

## **Motivation** 
The emergence of decentralized finance (DeFi) has introduced novel financial instruments, including on-chain options, which offer users the ability to hedge their crypto assets and speculate on price movements in a decentralized manner. This paper provides a comprehensive analysis of on-chain options within the DeFi ecosystem and compares them in various dimensions to their off-chain counterparts traded on centralized exchanges (CEXs).

## **Statement of Research Objectives**
The study begins with analyzing the fundamental characteristics of on-chain options, emphasizing their reliance on smart contracts, decentralized protocols, and blockchain networks. We delve into the mechanics of on-chain options, exploring aspects like collateralization, and expiration mechanisms, while also highlighting the advantages of transparency and censorship resistance inherent in DeFi options. In contrast, off-chain options traded on CEXs are examined for their established market infrastructure, liquidity depth, and regulatory considerations. While centralized exchanges offer a more familiar and user-friendly interface for traditional traders, yet they also introduce counterparty risk, potential downtime, and the need for trust in the exchange operator.
A key component of the empirical analysis involves a comparative assessment of the advantages and drawbacks of on-chain options and off-chain options. Factors such as liquidity, pricing mechanisms, cost, accessibility, and risk are thoroughly evaluated. Furthermore, the study delves into recent developments and innovations in the DeFi space, such as decentralized options protocols, automated market makers (AMMs), and liquidity provisioning strategies (underwriting options), and discusses how these advancements are reshaping the landscape of on-chain options.

Ultimately, this research seeks to inform market participants, traders, and blockchain enthusiasts about the distinct characteristics and trade-offs associated with on-chain options in DeFi when compared to traditional off-chain options on centralized exchanges. By presenting a comprehensive overview of these two options trading ecosystems, this paper contributes to a deeper understanding of the rapidly evolving world of blockchain-based financial derivatives. 

In the first phase, we are planning to empirically compare on-chain and off-chain options trades and option chains across the following dimensions. If the analysis points to an interesting finding the plan is to explain the differences in a theoretical framework.

### _1.	Liquidity_
Providing liquidity for on-chain options in the DeFi ecosystem involves a process known as underwriting, which plays a crucial role in facilitating the trading of these options. Underwriting options or providing liquidity involves users (liquidity providers) depositing assets into liquidity pools to enable trading for others. In return for providing liquidity, users receive rewards in the form of fees generated from trading activity within the liquidity pool. These fees are typically proportional to the amount of liquidity provided. In addition, they might generate a profit or loss depending on the trajectory of their underwritten position. Liquidity can vary significantly depending on the specific DeFi platform and the popularity of the options. 
### _2.	Pricing Mechanism and Implied Volatility_
On-chain options rely on decentralized pricing mechanisms, often utilizing mathematical formulas and oracles to determine option prices. Implied volatility is typically derived from the pricing mechanism employed by decentralized options protocols. Implied volatility is a critical component in determining option prices in DeFi, as it reflects the market's expectations regarding future price volatility of the underlying assets. Users can generally access transparent and decentralized sources of implied volatility, which enhances trust and reduces the potential for manipulation.

Off-chain options on centralized exchanges are priced based on the exchange's order book, where buyers and sellers set market prices. This can result in more efficient price discovery and tighter spreads. CEXs also have the advantage of offering more complex options strategies, such as spreads and combinations, which are not always available on DeFi platforms. Implied volatility is also a key factor in determining option prices. CEXs often calculate implied volatility based on the supply and demand for options contracts within their order book.

## **Practical Value of the Project**
The stability and efficiency of financial markets heavily rely on the crucial significance of derivatives. The results that we could provide in our paper can be useful for the enhancement and development of the current architecture of any option DEX or protocol. Besides, the paper would guide and educate the investor on how to navigate and access on-chain options and about their differences as compared to off-chain options. In addition, we want to educate the community about underwriting options and their earnings potentials when providing liquidity on a DEX and how this interacts with the existing DeFi landscape.

## **Benefits for your Foundation and Ecosystem**
You would sponsor a high-level academic research paper in DeFi and hence gain visibility among the academic community. Our current paper “Maneuvering and Investing in Yield Farms” (https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4422213) has been presented already at various conferences. 

In addition, we just held a one-day conference by the Collegio Carlo Alberto and the University of Turin, called ToDeFi: Torino Decentralized Finance Conference 2023 (https://www.carloalberto.org/event/todefi-torino-decentralized-finance-conference/), which promoted the highest level and up-to-date research in DeFi within the academic community. Speakers and discussants were selected among the most innovative junior researchers and established scholars. We are planning to make the conference a yearly event. Beyond the research support, we are potentially open to discussing a deeper cooperation. In particular, the Collegio Carlo Alberto hosts a postgraduate Master’s in finance, insurance, and risk management (Mafirm), which is a small high-quality program that has existed for more than 20 years. The program appears in several international rankings (e.g., 1st in Italy, 6th in Europe, and 25th worldwide in the quantitative finance masters' ranking by Risk.net). The students attending our master lectures are excellent but more importantly, really motivated.

## **Funding Requirement: Data and Research Assistant**
Dedicated firms such as https://www.amberdata.io/ad-derivatives offer access to various centralized and decentralized cryptocurrency trading platforms for options (trade history and historical option chains), which we would like to acquire for this project. In addition, we would like to hire a research assistant who helps us with various data-related tasks. Some of the pool data for liquidity provision can also be sourced for free via The Graph as done in our other projects (Li Naik Papanicolaou Schoenleber 2023). We want to emphasize that any amount of sponsorship or donation would be beneficial for us since we are trying to request funding from different funding sources to realize this project. We also emphasize that we would appreciate any support in helping to access specific on-chain data.

Items – Amount (EUR) 
1.	Amberdata.io data for one year – 10,500
2.	Research Assistant - 1,500
3.	Proofreading and submission fees - 1,000
Total: 13,000

## **The Team:**
Prof. Dr. _Lorenzo Schoenleber_ is an Assistant Professor in Finance at the Collegio Carlo Alberto and the University of Turin. He obtained his PhD at the Frankfurt School of Finance. He is also associated with the Fintech & Digital Finance Chair at Paris Dauphine University. His area of specialization is empirical asset pricing (option-implied information) and DeFi (Yield Farming). 

Prof. Dr. _Andrew Papanicolaou_ is an associate professor in the Department of Mathematics at North Carolina State University (NCSU). His PhD is in applied mathematics from Brown University. His research interests are computational finance and stochastic systems for control and optimization. The applications of this work include financial data analysis and the challenges associated with these highly complex data sets. My background is in probability theory and nonlinear filtering. 

Dr. _Siddharth Naik_ is a quantitative portfolio manager and trader with over 7 years of experience at institutional hedge funds (systematic macro and low latency, respectively) with extensive experience in trading fx, futures, and crypto instruments. He has previously published multiple papers on non-convex optimization mechanism design and trading crypto since 2017. Previously he was a CEO at RadioLytics a startup, which aimed at making spectrum tradable.

_Andrea Andolfatto_ is a Ph.D. student at Bocconi University and is currently working at Algorand Fintech LAB. His interests lie in asset pricing in particular household finance and machine learning, and Decentralized Finance. He holds a master's in Finance from the University of Turin and the Collegio Carlo Alberto. He is currently working on the role of liquidity providers and protocols in the dynamic of decentralized exchange rates.

## **Timetable** - Project Roadmap & Milestones - Expected Timeline for the Grant Completion
_Dates - Project stage_ 

10-12/2023 – Accessing, preparing, and processing CEX and DEX option data via the Amberdata.io API 
01-03/2024 – Processing and analyzing the option data across various dimensions (liquidity, pricing, implied volatility)
03-06/2024 – Investigate the earnings and losses from on-chain liquidity provision (DEX) 
06-08/2024 – First paper draft 
09-10/2024 – Submit to a journal

## **Useful Links:**
https://sites.google.com/view/lorenzo-schoenleber/menu
https://math.sciences.ncsu.edu/people/apapani/
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4422213
https://www.carloalberto.org/event/todefi-torino-decentralized-finance-conference/
https://www.carloalberto.org/education/master-in-finance/

**Comment by debbly** [comment]
Hi @lorenzoshoenleber, thank you for submitting a grant proposal however we are currently focused on funding open source tooling built on top of Lit. Good luck on your research!
