### ISSUE TITLE
Open Grant: Gated access to communities for Troop (+Lens Protocol)

### ISSUE THREAD

**Issue by nicnode** [LIT-Protocol/LitGrants#7]
# Open Grant Proposal: `Gated access to communities for Troop (+Lens Protocol)`

**Name of Project:** Troop Finance

**Proposal Category:** `integration-adoption`

**Proposer:** `MartinPaulLippert` & `LassGallard`

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

_Problem_
More than 70% of crypto investors collaborate on their investment strategies using social media platforms like Telegram or Discord, friend chat groups and KOL’s platforms. We have identified three opportunities: 1) KOLs and community leaders want to have gated access to their content to followers who contribute the most or are willing to pay for content. 2) Active members don’t get compensated for their research when they share it with KOLs. 3) Retail investors don’t have the time and knowledge to keep-up and research the space, thus use wrong metrics (like number of followers) to assess who to follow.

_Solution_
In our platform, users can create communities that are called troops. Troops discuss and collaborate on the allocation of their portfolios by connecting tokenised portfolios/funds of different crypto assets and DeFi strategies to a DAO (Decentralized Autonomous Organisation). The DAOs are used for the governance of the portfolio and the distribution of rewards, which will be given based on an on-chain reputation system that incentivises members to contribute and vote for profitable ideas and grants objective credentials to the contributors. Our platform will align incentives among and within communities and will bring together members with similar industry knowledge, expertise and interest, financial goals and risk profiles.
KOLs and active members can now collaborate closely with their communities and will be able to get compensated for sharing ideas and information. They might also decide to gate their communities and content to specific users. This would allow the community to share the rewards from the alpha (internal investment knowledge) generated among members.

## Value

**Content encryption**
Allows content creators and communities to restrict access to their Lens content so that they can monetise them by only allowing followers or collectors of the creator’s profile or members of a community to view the encrypted content. The risk is that Lens is extremely open and we have realised that the current version of communities and content is doesn’t allow for restricted access. This would be a deal-breaker for creators in our platform (it’s a feature they explicitly asked for), and it's a key feature that we need to achieve product-market fit.
 
**API and application Access control**
We will also be providing off chain applications and services to our users, Lit Protocol would allow us to control who has access to those applications and services. The risk behind not getting this right is giving access to sensitive information to malicious parties. 

**Execution Risk:** 
One risk would be dealing with the different access protocols for off chain applications and services. There is also the potential security risks with developing on the Lens Protocol and blockchain. 

## Deliverables

Our final deliverable will consist of the following components:
- React Front End application
- Allows user to post and monetise content
- Provide access to the troops voting and proposal system
- Allow users to view troop activity and value
- Provide access to the discussion forums
- Lens integration
- Solidity Smart contracts
- Provide on-chain functionality for managing the troops
- Discussion forums 
- Provide an off-chain discussion platform backend
- Min. 20 communities onboarded

### **Milestone 1:** 
Enabling closed communities through Lens NFTs

_Details:_

- Creation of troops 
- Creation of gated and monetised content
- Implementation of the Lens Protocol for social interaction
- Implementation of encrypted content through the Lit Protocol 
- Development of a Front-end React application

_People:_ 

- 2x Developer
- 1x Product Owner

_Funding:_ EUR 5000
_Time:_ 31 July 2022 (already in progress)

### **Milestone 2:** 
Link an Enzyme vault to a troop for viewing only

_Details:_

- Integrating the ability to add and view Enzyme vaults within the Troop application
- Make Enzyme vaults created in Troop private
- Restrict visibility only to members of specific troops

**People:** 

- 2x Developer
- 1x Product Owner

_Funding:_ EUR 2000
_Time:_ 6 August 2022

### Milestone 3:
Implement a strategy proposal and voting mechanism to change the allocation of the portfolio (=MVP ready)

_Details:_

- Create a strategy proposal submission process
- Create a strategy proposal voting mechanism
- Create long term proposal performance tracking
- Create participation Reward mechanism
- Secure proposal when required
- Secure and add ACL to external services
- Create mechanism to update Enzyme Vault according to the selected strategies

_People:_ 

- 2x Developer
- 1x Designer
- 1x Product Owner

_Funding:_ EUR 10 000
_Time:_ 3 September 2022

### Milestone 4: 
Onboard 7 pilot communities to Troop to test this 

_Details:_
Walk our 7 pilot communities through the onboarding process
_People:_ 
1x Product Owner
_Funding:_ EUR 650
_Time:_ 10 September 2022

### Milestone 5: 
Iterate on feedback and fix bugs

_Details:_

- Have feedback session with our pilot customers
- Assess the feedback to understand the impact and time to implement changes

_People:_ 

- 2x Developer
- 1x Designer
- 1x Product Owner

_Funding:_ EUR 7500
_Time:_ 30 September 2022

### Milestone 6: 
Onboard 12 applicants of communities. Walk through Troop test creation

_Details:_
Walk the initial 12 applicants on our waitlist through the onboarding process
_People:_ 
1x Product Owner
_Funding:_ EUR 1300
_Time:_  14 October 2022 

### Long-term project: Development of additional features 
_Details:_

- Connect to different DeFi investment tools and platforms 
- Create a tiered access system to individual troops based on reputation
- Provide additional content options for content creators
- Implementing the token fees and rewards mechanism

_People:_ 

- 2x Developer
- 1x Designer
- 1x Product Owner

_Funding:_ 10 000 euros per month
_Time:_ Ongoing

## Total Budget Requested

Salary 2 Developers (entire project): EUR 15,000
Salary Product Owner (entire project): EUR 7,500
Designer agency: EUR 3,500
IT costs: EUR 450

Total Budget: EUR 26,450 

## Maintenance and Upgrade Plans

Once the MVP is developed and some communities are onboarded, this will give us leverage to find investors and hire more members. Getting funding for growth on that front will enable the development of the next steps of the project and to kick-start additional marketing efforts to potentiate the adoption of our tool, and thus the mass use of Lit Protocol.

# Team

## Team Members

Martin Lippert

Nico Gallardo

Gonzalo Marquez

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/martinpaullippert/

https://www.linkedin.com/in/nico-gallardo/

https://www.linkedin.com/in/marquezgonz/

## Team Website

https://www.troop.finance/

## Relevant Experience

**Martin (Developer):**
Martin has a degree in Computer Science and Economics and a degree in Psychology. He has over 25 years of development experience in various industries, including FinTech, RegTech and Logistics. 

He has worked on a dissemination platform with a 24/7 uptime requirement and delivered trading data in real time to members of the Johannesburg Stock Exchange (JSE). He also developed a white-labelled online tutoring platform, which allowed students and tutors to have a video with collaborative documents. Microsoft, the Dubai Government and various training institutes used this platform.

Over the last seven years, Martin has grown and mentored development teams in South Africa, Dubai and The Netherlands. 

**Nico (Product Owner):**
Nico pursued a career in FinTech, gathering his first experience in Product Development at Raisin in the Investment Products team. His interest for crypto kickstarted then in 2018, which culminated in the creation of his Bitcoin education platform and current Web 3 projects.

Before that, he worked with many start-ups through his experience in incubators and accelerators. Thanks to his creativity and resourcefulness he is constantly bringing innovative ideas to the table. 

His strengths lie in the product and strategic side of the business, as well as business development. His experience with tech teams allows him to connect and communicate on a deeper level with developers.

**Gonzalo (Front-end developer):**
Gonzalo is a frontend developer. He has 6 years experience with React and has developed the front-ends of many start-ups in different fields. His latest projects include Kinnek and Rally, where he was the only frontend developer.

He also got involved at the early stage of a project called habla.ai. In this case, he engaged not only with the frontend, but managed the backend and everything related to AWS, DynamoDB, Lambda and S3.

He started diving into web3 in 2019, and is working on transferring his skills into this new, rapidly growing industry.

## Team code repositories

https://github.com/MartinPaulLippert
https://linktr.ee/lassgallard
https://github.com/​​marquezgon

# Additional Information

We became aware of Lit Protocol at the beginning of the year, when Jordan approached us to collaborate. We immediately saw the potential to use this offering, but weren’t ready to implement it. Just a couple of weeks ago, we reached out to him again and after a quick talk we immediately started diving deeper into Lit and began its implementation with Troop. Running through the docs, we came across the grant programme and realised it would be a much better fit for us than some of the other grants we were considering, because it would help us focus on building what is truly meaningful for our platform.

Please reach out to nico.gallardo@troop.finance to discuss the grant agreement and next steps. Additionally, you could ask Jordan to include the relevant representative in the Telegram group we’ve created with both projects.

**Comment by debbly** [comment]
Hi @LassGallard, thank you for submitting a proposal! This proposal's scope is bigger than we have capacity to support at this time. 

The relevant Lit Protocol <> Troop Finance piece is in milestone 2. If you can give a breakdown of how you plan to integrate Lit and what you plan to open source from that portion, I'd love to keep discussing what support for that might look like!

**Comment by LassGallard** [comment]
Hi @debbly, thanks for your prompt answer! Here is a summary of what the relevance for Lit means for each milestone. As you said, maybe it's a good idea to start with Milestones 1 and 2, which is for what we most urgently need the integration with Lit. In the Value section we lay out what it means e.g. for off-chain applications. All of it open-source of course. Here is what it means for these milestones:

Milestone 1: Troops need to have restricted access. Thus the creation of these communities on Lens Protocol with a way to gate them is important. Additionally, some people in the platform might want to restrict access to specific content. This is also something we will develop for Lit Protocol. All this could be used by other projects who are integrating Lens with Lit. 

Milestone 2: Restricted access to these vaults with limited visibility for a selected amount of Troop users. We could develop this integration with Enzyme as open source as well.

Maybe let's create a group-chat (or join the current one with Jordan) to discuss scope and support capacity? Here is my tg: t.me/LassGallard
