### ISSUE TITLE
Small Grants: Lit Protocol Package for the Element Web Framework

### ISSUE THREAD

**Issue by drpitman76** [LIT-Protocol/LitGrants#73]
### 1. What is your project?
**Lit Protocol Package for the Element Web Framework**

This project is to create an extension package to be used primarily by any web applications built on the Element framework. The package will encapsulate client-side Lit functionality into a set of discrete web components. This will enable simple usage of Lit by developers of web applications within **any framework**, not just Element - as Element components are completely portable.  

It will be published via Github/CDN, IPFS and to the upcoming [Element Package Repository](https://elementhtml.dev/repository).

**Github Repository for Package**: https://github.com/elementhtml/package-litprotocol
**Demo page for Package**: https://package-litprotocol.pages.dev/

**Github Repository for Element Framework**: https://github.com/elementhtml/element
**Main website for Element Framework**: https://elementhtml.dev/

### 2. How is Lit used for this project? (max 100 words)

The entire current Lit API will be examined and encapsulated into a suite of easily understood, accessible, portable, extendable and reusable custom web components.  This will lower the barrier of entry for developers and allow them to focus on concerns like "I want to encrypt this data here" or "I need a sign-in experience there" - and simply drop in the solution - rather than thinking "How do I use Lit to ...?".  

For example in the current demo page a component to encapsulate Lit signature functionality has been drafted, the markup is:   `<meta id="lit" is="lit-signature">` , and the directive to print the signature object to the browser UI when it is created is: `$(~|#lit!signature) >> ($string($.signature, true)) >> $(:|pre)`.  Element enables a lot of reliable functionality with minimal coding that removes all boilerplate JavaScript and minimizes the learning curve - this will help make Lit Protocol more accessible. They simply want a signature, so they put a `lit-signature` component in and the API to use it is immediately standardized.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The scope of this project is to initially determine the required set of components to best encapsulate Lit functionality in Element applications, and then to complete and publish that set of components. Likely components will include `lit-signature`, `lit-wallet` and `lit-action` components at the very least.

This grant will enable me to spend sufficient time on this to thoroughly understand where best to target component encapsulation, to understand which components are optimal to cover the most likely and frequent use cases for Lit in Element applications, and then to architect components which make that as intuitive, bug-free and simple as possible for other developers.

It will also give me sufficient time to create thorough tests, demos and documentation for each component, ensuring that once the package is released, developers can use it with confidence as a "black box" of Lit functionality. 
 
### 4. Is this project open source?
Yes, MIT Licenced

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Yes, let me know what is required and when.

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Lit Protocol prizes? Include links here if available:
No...

### 7. Total Budget Requested

**2500 USD**

- **Milestone 1**: research, experiment and create initial prototypes of core Lit components to cover major functions of the Lit API. Must at least cover common sign-in scenarios (with and without wallet / long and short-lived / various auth methods), encryption/decryption and Lit Actions functionality. The goal will be to cover the most frequent 80% of use cases for web applications and remove the Lit-specific learning curve from developers in situations where they want to do relatively common and simple tasks that shouldn't require an in-depth understanding of Lit Protocol to make happen. **Budget: 1500 USD / 3 weeks**
- **Milestone 2**: complete the required components in detail, including full testing, demo pages, and documentation. Publish to IPFS as well as a Github based release for use with popular Javascript CDNs such as JSDelivr. **Budget: 1000 USD / 2 weeks**

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
David Pitman, david.pitman@cloudouble.com, https://github.com/drpitman76. Core developer
 
* How did you learn about our grant program?
Been following Lit for a while as I know it will be critical to use to create a 100% client-side web application ecosystem. 

* If your project was created as part of an event or hackathon: No

**Comment by drpitman76** [comment]
Any thoughts on this?

**Comment by drpitman76** [comment]
Implicit in creating this package would be using a JavaScript SDK which this package would really just be a wrapper for, however in the process of looking further into this, I can see a more compelling need to create a simpler, lightweight and dependency-free browser-native JavaScript SDK. 

I know there is already a JS SDK, and I definitely don't mean any disrespect in any way to the developers of the current JS SDK, however it is very nodeJS-heavy, heavy in the kB, and therefore unsuitable for light-weight usage in an app which needs to prioritize performance, including initial load. It is also extremely difficult to use within a vanilla JS environment.

Looking at this page: https://developer.litprotocol.com/v3/sdk/installation#sdk-installed-for-client-side-usage directions , 
statements such as 

```
import * as LitJsSdk from "@lit-protocol/lit-node-client";
```
 
 Simply *just don't work* inside a browser vanilla JS application! And I believe that the SDK must be first written to support vanilla, and then adapted from there, not the other way around. That way it is made available to the widest possible audience.
 
 Anyway, I want to re-purpose this  grant application into developer a light-weight JS SDK fully out-of-the-box compatible with vanilla, web standard compliant JavaScript. It would open Lit up to so much more use cases than it currently has.
 
 However, I will wait to hear a response from this grant application before doing that, as so far it has been silence over here and I don't want to be putting in the work of creating the application for it not to be reviewed.

**Comment by Aaryan-R-S** [comment]
Hey @drpitman! This is proposal is incomplete. 

One of our engineers replied:

> I’m not sure how many people actually will/want to use Element framework for Lit, personally i’d must prefer to have react hook components encapsulating Lit functionalities where we would capture much wider audience.
> milestone 1: “research, experiment and create initial prototypes…” before the proposal i’d have thought you’ve already done that. I’m more interested to see a list of features rather than paying someone to play then come up with the features later on (again, that should’ve been the proposal)
> milestone 2 should be milestone 1

We will be happy to see an updated version of this!

**Comment by drpitman76** [comment]
I will create an updated version - however I want to point out that milestone one is actually the real work of this application: "research, experiment and *create initial prototypes*" --- just because I put the word "experiment" in there doesn't mean this milestone is "playing around", I was being upfront about what everyone does at that point in a project - understand the best way to do the task ahead.

In the Element framework, web components are inheritable, so the "initial prototypes" are the underlying base classes which encapsulate 90% of the real functionality of the end-user components. That's why milestone one was bigger in terms of cost than milestone two - it represents 90% of the real work of the project.

Also, Element components are just core web standards compliant custom web components and can be used in any other framework (including React if desired), so this solution is the most generalisable possible web component solution.

Anyway, since submitting this original proposal I have realized that the immediate bottleneck is the absence of a lightweight, easy JavaScript solution with drop-in compatibility for vanilla JavaScript and service workers of all kinds.

So I will re-submit a proposal to create that as an Open Grant project (as that is a broader scope than this project) and also re-submit this current project covering just the Element framework components. I'll have this in the next couple of days...

Thank you for your responses and look forward to continued dialog, understand and forward motion!

- David P.

**Comment by drpitman76** [comment]
I have submitted an Open Grant application for a JS Worker SDK, it is over at https://github.com/LIT-Protocol/LitGrants/issues/75

**Comment by Aaryan-R-S** [comment]
Thanks @drpitman76!
