### ISSUE TITLE
Open Grant: Decentralised platform for authentication and authorization and cross-platform data integration solution

### ISSUE THREAD

**Issue by daniel-ospina** [LIT-Protocol/LitGrants#78]
# Open Grant Proposal: Decentralised platform for authentication and authorization and cross-platform data integration solution

**Name of Project:** TogetherCrew

**Proposal Category:** Integration-adoption 

**Proposer:** daniel-ospina

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:** yes

# Project Description
In communities, user data is fragmented across platforms, leading to overwhelm,  confusion, and missed opportunities for community builders. Users also deal with fragmented identities, leading to poor UX having to input/authenticate multiple credentials over and over as they use different platforms and services. Finally, this same fragmentation leads to app developers having to do extra work creating multiple authentication methods.

TogetherCrew has already built a community analytics solution that gathers data from the most popular community platforms (discord, telegram, github, etc), and provides behavioural insights and automations to improve community member experience and unlock growth. And our solution is being used by 100+ communities including Optimism, Aave, Pocket Network, etc etc. 

Our vision is to grow from this base and become a decentralised platform for authentication and authorization, unburdening apps from user management complexities. We want to allow users to link various identifiers to their master profiles, giving them the ability to grant and revoke identity visibility across apps and platforms. This provides smooth UX and privacy control for users, 360 insights for community builders, and also a handy solution for other app developers.

The resulting tool will be a module that can be used by us and other 3rd party applications, via API, to link the identifiers of users while providing users with powerful data management control over who has access to their identifiers. We have already spoken with multiple applications (Questbook, MeetWithWallet, Collabberry, etc.) that are interested in also using this solution.

## Value
We understand that we are dealing with sensitive user data and that encryption is critical. Additionally, we want users to own their data. Using Lit Protocol, we believe that we can achieve both security and data ownership.
By providing this solution, we unlock a powerful use-case of Lit protocol, that can be easily integrated in thousands of apps and serve millions of users.

## Deliverables

A application live on Arbitrum mainnet and expandable to other chains, including authentication and linking API, SDK, EVM-compatible contracts, and a user interface. The application enables users to authenticate and link off chain credentials, own their data (attestations of ownership of credentials), and manage data access to the attestations. Moreover, the application serves as a modular middle layer, where other apps can request from users access to the data without requiring users to go through a complicated UX of authenticating every credential individually.

## Development Roadmap

**Authentication & Linking API**
PEOPLE
- https://github.com/Behzad-rabiei application engineer
- https://github.com/cyri113 architecture & engineering review

BUDGET
$4,000

TIMELINE
Estimated Delivery: ~20 days
If stating 8th July, delivery 2th August

PROCESS

- Create authentication processes for Google, Discord, Discourse, and Wallet.
- Creating a linking process responsible for verifying that user credentials are valid.
- Create a process for encrypting user credentials for any provider using Lit Protocol.
- Create signed Attestation (EAS) payload data for including encrypted data.
- Create a solidity contract that allows users to grant/revoke the permission to decrypt attestation data using Lit Protocol EVM Contract Conditions.

**SDK**
PEOPLE
https://github.com/Behzad-rabiei application engineer
https://github.com/cyri113 architecture & engineering review

BUDGET
$2,000

TIMELINE
Estimated Delivery: ~10 days
5th August to 16th August

PROCESS
- Create an SDK to facilitate integration with protocol. The SDK will leverage the Lit Protocol SDK, EAS SDK, and abstract the querying of on-chain data. It will have the following capabilities:
- auth. Redirects the user to authenticate with a given provider.
- getHash. Generates a SHA-256 hash of the input. The hash can then be used as a parameter in an EAS query.
- getAddressesByCredential. Queries EAS and returns all addresses that have verified a given credential.
- getAttestationsByAddress. Queries EAS and returns all the attestations issued to a given address.
- getPermissionByAttestation. Queries the contract and returns whether an app has the permission to decrypt attestation data.
- decryptAttestation. Uses Lit Protocol to decrypt data.
- link. Given valid credentials, this function will receive a signed attestation payload from the API and prompt the user to sign a transaction to generate a on-chain Attestation using EAS.

**User Interface**
PEOPLE
https://github.com/mehdi-torabiv application engineering
https://github.com/cyri113 architecture & engineering review

BUDGET
$4,000

TIMELINE
Estimated Delivery: ~20 days
22nd July to 16th August

PROCESS

- Create an interface to allow users to:
- Sign in with ethereum
- Authenticate with available providers
- Create an on-chain Attestation (EAS) containing encrypted user credentials
- View/grant/revoke the permission to decrypt attestation data
- Create an interface to allow app developers to:
- Configure application
- View (accessible) user profiles

Application documentation: https://rndadocs.notion.site/Identity-Authentication-Platform-IAP-64a6eb8d3d2c4ac58f50e5c26812fc5b?pvs=4

## Total Budget Requested

10,000 USD equivalent

Budget breakdown*

- Development for milestone 1: 4,000
- Development for milestone 2: 2,000
- Development for milestone 3: 4,000

*marketing costs will be beared by TogetherCrew

## Maintenance and Upgrade Plans
We already have a live product in TogetherCrew, with 100+ communities using it. This grant allows us to expand and build on top of what we have using lit protocol to unlock powerful new functionality. Maintenance will thus be carried out as part of our routine, ongoing operation. 

# Team

## Team Members

- Danielo  (contact person) - Instigator at RnDAO and CoLead at TogetherCrew. Previously, Head of Governance at Aragon, 8 years experience in Organization Design consulting (clients include Google, BCG, Daymler, The UN, and multiple startups), founded two startups, and served as visiting lecturer at Oxford University.
- Ashish - co-lead at TogetherCrew, Previously at Tata, working at the intersection of innovation and customers. 8 years in startup incubation and innovation. Launched and repositioned multiple brands. Twitter: twitter.com/a_gangrade/ 
- Cyrille Derché - Tech lead at TogetherCrew. Bsc. Computer Science. Ex-Accenture, 8 year as co-founder and CTO of SaaS company helping medical device manufacturers deliver product data + documentation to healthcare professionals (handling of sensitive data). Builder of products, processes, and teams.  Github: https://github.com/cyri113 (private, ask us for access if needed)
- Katerina- Co-lead TogetherCrew. Ph.D. using social network analysis. Since 2016 she is co-instructing a graduate course on data analytics for HR at Northwestern University. She has also co-organized the Learning in Networks sessions at the International Conference of Social Network Analysis (2018 - 2020), and previously advised a people analytics company on social network metrics. Twitter: [ twitter.com/katerinabohlec](http://twitter.com/katerinabohlec) Blog:netnigma.io Github: https://github.com/katerinabc/
- Our team additionally counts with 2 core developers ([Behzad](https://github.com/Behzad-rabiei) and [Nima](https://github.com/mehdi-torabiv)) and if needed we can call upon other members of RnDAO (totalling 40+).
- 

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/conductal/
https://www.linkedin.com/in/ashishgangrade
https://www.linkedin.com/in/cderche/
http://linkedin.com/in/katerinab

## Team Website
https://togethercrew.com

## Relevant Experience
We’ve been in Web3 since 2017 (ex-head of governance at Aragon) and have 8+ years of experience building applications that manage sensitive data (previous CTO role in MedTech).
As TogetherCrew we have now been building for two years and have 100+ communities using our product (Optimism, Celo, Aave, PockeNetwork, etc.).
Additionally, we have partnered with Snapshot and Arbitrum to launch the reputation tool and decentralized Platform for Authentication and Authorization we’re proposing in this grant.

## Team code repositories
https://github.com/togethercrew

# Additional Information
Found you: Researching options of infrastructure to integrate
Email: info@togethercrew.com

**Comment by davidlsneider** [comment]
Hey @daniel-ospina - thanks for the thoughtful application here! At this point, we can not accept this application since the grants program is tightly scoped to developer tooling, opposed to grants for end user products. We wish we could fund every promising product, but that's just not feasible. 

If you're looking for a boost in terms of getting starting with this product, Lit has grants at ETHOnline, which starts Aug 25th and runs for 2 weeks.
