### ISSUE TITLE
Small Grants: Simplr Events - Verifiable and trustless secondary ticket marketplace

### ISSUE THREAD

**Issue by codebuster22** [LIT-Protocol/LitGrants#79]
### 1. What is your project? (max 100 words)

- Problem Statement: Secondary Ticket market is an unorganized mess. Primary ticket sellers don’t have infrastructure to support reselling of tickets and the existing secondary market places are full of fake ticket sales and scam. No infrastructure exist to resell tickets in a verified and trustless manner.
- Market Size: Based on studies conducted, the Secondary Ticket Market has $2 Billion market size with a 9% CAGR.
- Project Idea: A secondary ticket marketplaces for verifiable and trustless trading of tickets.
- Product Description: The platform will facilitate creation of ticket proofs of existing ticket using Reclaim Protocol to validate the authenticity of ticket and create a proof of humanity using social metric (Linkedin, Instagram, Twitter or other social media platform) for the seller. Once a ticket proof and proof of humanity is created, the ticket will be converted to NFT and the ticket data will be encrypted using Lit Protocol. The NFT can now be traded on the platform with a pricing cap decided based on the type of event or by the event oragnizer.
- Future: Direct integrations with existing ticketing infrastructure or with the event organizers to add direct append operations on the ticketing infrastructure.
- Notes: The product is not a Web3 product, it’s just a product which uses Web3 technology to bring verifieablility and trustless features to most needed industry. The product is fully focused on Web2 users and aim to bring out real use case of Web3 to masses.

Specs: https://github.com/codebuster22/simplr-events-specs
We can share the MVP repo as well, but it's private right now, so kindly share your github usernames to give you access to the codebase)
Demo: https://x.com/encrypted8532/status/1747853389755789804

### 2. How is Lit used for this project? (max 100 words)
We are using Lit to encrypt the ticket data and store them in a distributed system, with access to decrypt only by NFT holder and access controlled to Event organizer. In future using Lit Actions to submit proofs from reclaim provider.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This grant will give us initial funding to build a working alpha version of the product and start next steps in raising capital for future development. Initially, we plan to work on getting following features developed mentioned in Implementation section.
 
### 4. Is this project open source?
Not yet decided, but we will make certain parts open-source as part of public goods.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the two month period?
Yes, we will frequently submit a report which will include following as we progress:
- User Interviews and documentations
- Reviews from event organisers
- Number of users
- Number of tickets resold

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Lit Protocol prizes? Include links here if available:
N/A

### 7. Total Budget Requested
* Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Requesting a budget of 2,500 USD to get the product developed with following features:
Implementation:
1. Simplr Events will use Reclaim protocol to generate two proofs:
    a. Ticket Authenticity: To ensure only valid tickets are traded.
    b. Social Proof: To give a score to seller which will be reflected on the marketplace reflecting the social trust score.
2. Once tickets are authenticated, the tickets will be encrypted using Lit Protocol ensuring the privacy of the seller and prevent someone else from using the ticket without purchase.
3. Encrypted tickets are converted to NFT and listed on marketplace.
4. Buyers can buy tickets after browsing through the listed tickets based on event, trust score and ticket proof.
5. Sellers receive payment for the ticket sold which can be off-ramped easily.
In-depth mechanics and diagrams can be found here: https://github.com/codebuster22/simplr-events-specs

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Existing Team:
- Encrypted8532 (Mihirsinh Parmar): A solidity Engineer for over 3 years with degree in computer science generating total volume of over $20 Million. Having built a product earlier, I have the experience in leading teams to build out technologies and products that make impact. I have worked with Movement Labs, Curve Labs and contributed to Safe Global, Lit Protocol, hyperlane and Toucan.
- Baps Patil (Bapusaheb Patil): A Product Designer with 6.5+ years of experience in designing human behaviour driven products. Baps have won multiple awards in UX and best website categories over year. Having built micro-products and having them acquired, he has the knowledge of moving fast and prioritising quality.
- Angel Lakra: Frontend Engineer with an experience of 3 year with a degree in computer science. Angel has been workin in Web3 for 3 years, building high performance dApps and integrating any protocol that has been thrown to him. dApps have generated total volume of over 1 Million USD.

Key Hires:
- Business Development Lead: We will need a person who can position our product in front of major events and platforms to form a partnership and drive growth for the product.
- Community: An Intern who can build a vibe and narrative around the product positioning the product in front of event attendees and bring organic traction to the platform.

Recent Work:
https://spark.litprotocol.com/enabling-private-on-chain-txns/
https://axol.io/
https://www.prime.xyz/ (only smart contracts)
https://wagr.gg/
https://www.sdvvvorks.io/
https://bipzy.com/

* How did you learn about our grant program? - Previously worked on a different Lit Grant with Curve Labs on Lit Private Transaction SDK
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal, OpenSea) - no
  * Please link to your submission - N/A

Note: This 2,500 USD is not enough to get the product developed and take it forward, as part of maintaining transparency, we have also applied with the same proposal for Arbitrum grant.

Contact:
Telegram: https://t.me/encrypted8532
Email: mihirsinh@chainlabs.in

**Comment by davidlsneider** [comment]
Hey @codebuster22 - this seems like a really awesome product! At this point, the constraint over here is that this Lit grants program is focused on OSS tools that make it easier for other developers to build on Lit and providing startup capital to new products isn't in scope. I'd suggest that you check out some of the web3 accelerators to pitch this concept to!

**Comment by codebuster22** [comment]
Thanks @davidlsneider 
We have applied for Arbitrum Grants and will be applying for other accelerators.
Can you make some connections?
I previously worked with Curve Labs and did work on an SDK grant from LIT in 2023.
