### ISSUE TITLE
Open Grant: BackedBy, a decentralized payments processor and crowdfunding subscription platform

### ISSUE THREAD

**Issue by cshowley** [LIT-Protocol/LitGrants#8]
# Open Grant Proposal: `Project Title`

**Name of Project:**
BackedBy

**Proposal Category:** Choose one of `app-dev`, `integration-adoption` , `technical-design`, `docs` , `research`   Learn what these categories are here: {https://github.com/LIT-Protocol/LitGrants/tree/main/open-grants}"
`app-dev`

**Proposer:** cshowley

**Do you agree to open source all work you do on behalf of this grant and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"
Yes

# Project Description

BackedBy is a distributed payment processor for creators (demo live at https://backed.by/). It provides creators an easy way to bring their business and audience to web3. Current content platforms charge exorbitant fees which eat into creators' gross revenue, and both the platform and creators rely on the existing financial infrastructure for payment processing. Creators also have no recourse for inappropriate demonetization or banning, as they do not truly own their connection with their audience. 

BackedBy uses the power of web3 to give creators a way to post content and directly collect payment from their audience through the sale of membership subscriptions. The BackedBy platform itself is monetized through a 1% fee on all transactions on the platform.

## Value

BackedBy’s long term goal is to give creators complete control over distribution to their supports by managing payouts and messaging through decentralized file storage that isn’t subject to asymmetric enforcement of perceived TOS violations. Creators’ content is stored on IPFS using Filecoin’s [web3.storage](http://web3.storage/) service, and premium content secured by Lit protocol for decentralized access control; only subscribers to a creator’s paid tiers grants access to that content. If this isn’t completed then data stored in the cloud will always be subject to third party interference. Decentralized data storage couple with privileged access using Lit represents data that is owned solely by its creators.

## Deliverables

The project is currently deployed to Polygon testnet, available at backed.by. All data posted by creators is stored on IPFS. We aim to deploy to the Polygon mainnet within 2022.

## Development Roadmap

1. 
Functionality: Demo/Prototype launch on the polygon testnet - a functional version of BackedBy that allows creators to make profiles, mint $PROJECT tokens, set up tiers for membership access, and post content. Subscribers can choose a membership tier for purchase to access content. All revenue from membership purchases are distributed to $PROJECT token holder. 
Devs required: 5, for contract writing, frontend UI, writing and recording tutorial videos/FAQ docs, and QA
Funding required: N/A
Completion date: 7/1/22 (completed)

2. 
Functionality: Stablecoin support - Creators can choose to list memberships for sale in stablecoin prices or MATIC token prices. Transactions can be performed with stablecoins or MATIC tokens, based on creator’s choice.
Devs required: 2, for contract writing and QA
Funding required: 1,000
Completion date: 8/1/22

3. 
Functionality: Recurring payments - Subscribers can choose to allow the BackedBy contract to process recurring payments to automatically renew memberships on a monthly or yearly basis.
Devs required: 2, for contract writing and QA
Funding required: 2,000
Completion date: 8/1/22

4. Distributed File storage - all creator content encrypted and hosted on a distributed file storage service. Decentralized access control to content for membership NFT holders provided by Lit protocol.
Devs required: 2, for contract writing and QA
Funding required: 4,000
Completion date: 8/1/22

5. 
Functionality: Launch of version 1 on Polygon mainnet - All features of the demo/prototype launch with support for desktop web browser and a mobile app. Included features detailed above; stablecoin and recurring payment support, project governance, distributed file storage, monetized message. All with easy onboarding through multiple popular mobile and desktop web3 wallets.
Devs required: 5, for contract writing, frontend UI, writing and recording tutorial videos/FAQ (which all need to be updated once new features are integrated)
Funding required: 10,000
Completion date: 9/1/22

6. 
Functionality: Project governance by $PROJECT token - Backers ($PROJECT token holders) can vote on what they want to see next from a creator or give creative projects direction.
Devs required: 3, for contract writing, UI, and QA
Funding required: 3,000
Completion date: 10/1/22

7. 
Functionality: Monetized messaging - creators can choose to accept +/- charge for direct messages from fans.
Devs required: 3, for contract writing, UI, and QA
Funding required: 4,000
Completion date: 10/1/22

8. 100 creators onboarded - 18,000 - marketing and outreach efforts focused on onboarding a diverse set of creators with successful premium membership profiles on web2-based competitors such as patreon. These creators, who have experience with successful monetization of paid content, would be the founding creators and core of the BackedBy platform, and would be able to bring proven content to the platform quickly.
Devs required: The whole team as we manage marketing and outreach to creators
Funding required: 18,000
Completion date: 10/1/23

## Total Budget Requested

Total: 42,000

1. Stablecoin support: 1,000
2. Recurring payments: 2,000
3. Distributed file storage: 4,000
4. Launch of version 1 on polygon mainnet: 10,000
5. Project governance: 3,000
6. Monetized messaging: 4,000
7. 100 creators onboarded: 18,000

## Maintenance and Upgrade Plans

We project long term growth of the site as more and more creators onboard. We plan to allocate a portion of the site's treasury specifically toward development of new features, maintaining the project, and hiring additional developers if needed. The income stream of the site allows it to generate revenue immediately directly proportional to the popularity of its creators given its 1% fee structure.

# Team

## Team Members

Boris Chobrutskiy
Dax Herrera
Charlie Showley
Garrett Tynes
Joshua Erickson
Brandt Hill
Pete Oxenham
John Bojtor

## Team Member LinkedIn Profiles

linkedin.com/in/daxherrera
-
linkedin.com/in/cgshowley
linkedin.com/in/jeffrey-garrett-tynes-08a08bb0
https://www.linkedin.com/in/josherickson/
https://www.linkedin.com/in/brandt-hill-8271b218/
-
https://www.linkedin.com/in/john-bojtor-00487319b/

## Team Website

https://backed.by

## Relevant Experience

Boris Chobrutskiy has a BS and MS in molecular biology from UCSD and an MD from University of South Florida, developed Adaptive Match, a bioinformatics app for discovering T-cell targets for the next generation of cancer therapy, and involved in other projects bringing healthcare to web3.

Dax Herrera has a BS in Computer Science from CalTech, the CTO of Collector Crypt, a web3 project bringing the world’s collectibles onto the blockchain, and co-founder of Foundation Digital, a digital marketing company serving Fortune 500 companies. He runs several successful comedy podcasts supported by thousands of backers at patreon.com.

Charles Showley has a BS in physics from Cal Poly SLO, an MS in astrophysics from SFSU, a senior data scientist who has developed several state of the art machine learning models for natural language processing which serve thousands of clients across multiple industries.
Garrett Tynes has a JD focused in Intellectual Property from the University of New Hampshire. He has certificates specializing in Intellectual Property Law and Entertainment Law, and has worked with large profile brands in areas of IP licensing, trademark, and copyright issues.

Joshua Erickson, dropped out a Network Systems Admin AAS to pursue a career in Information Services for outstate mid-west accounting firms.  Though preferring to be in the background, his work has helped multi-million dollar companies benchmark their productions and business costs against the wider industry.

Brandt Hill graduated Magna Cum Laude from Kansas State University with a BS in Computer Engineering and minors in Computer Science and Mathematics. He worked as a student researcher on behalf of Sandia National Labs, and has industry experience in the Intelligent Transportation Systems, IoT/Embedded Systems, and FinTech. Brandt contributes to open source projects in his free time.

Pete Oxenham is an experienced project manager across both hardware and software products, placing a heavy emphasis on design, user experience, and product scalability. Most recently founded Chatter.dev, an industrial IoT analytics company.

John Bojtor has an advanced diploma in cyber security and is currently working as an IT Security Operations Officer. Over the last three years he has been developing in Web3, coming from C# and .NET. Starting with a SafeMoon fork, then a completely on chain NFT collection. And recently creating a gaming and betting liquidity pool as part of the Chainlink 2022 Spring hackathon.

## Team code repositories

https://github.com/BrandtHill
https://github.com/ParanoidSyntaxError
https://github.com/cshowley

# Additional Information

Searched for grants directly on Lit’s website after integrating the protocol on the app

boris@backed.by

We have 4 simple goals with BackedBy:

1. Provide a platform that would give creators an easy onboarding experience in bringing their content to web3.
2. Provide creators with web3-exclusive tools such as minting collectible membership NFTs and $PROJECT tokens for investors. 
3. Provide creators with direct ownership of their connection with their audience through the power of open and transparent interactions between creators and subscribers on the blockchain. 
4. Provide fans of creators a way to access premium content and collect NFTs through purchase of membership NFTs. 

All content stored in a decentralized fashion. All payments handled without intermediaries. All creators with full control of their content, and freely available for anyone in the world to access.

**Comment by debbly** [comment]
Hi @cshowley, interested in learning more about your project!
At this time we are not supporting the full product developments and we are focusing on supporting Lit integrations. We'd be happy to help you all find additional funding to support your project as our partnership grows :).

The most relevant portion for Lit to support is the `Distributed file storage: 4,000` step.

Could you elaborate more on how you plan to open source your project?

**Comment by cshowley** [comment]
Sorry for the delayed response, I wasn't notified that you'd messaged back.

We've since been contacted directly by David so I can close off this issue for now. Thanks!
